package:
    name: gorgon
    version: 3.0a

build:
    number: 0

source:
    path: {{RECIPE_DIR}}/../

requirements:
    build:
        - cmake >=3.4
        - python 2.7.*
        - boost         # [not win]
        - boost-gorgon  # [win]
        - fftw
        - freeglut  # [not osx]
        - setuptools
    run:
        - python 2.7.*
        - boost         # [not win]
        - boost-gorgon  # [win]
        - fftw
        - freeglut  # [not osx]
        - termcolor
        - pyqt
        - pyopengl
        - vs2015_runtime  # [win]

about:
  summary: Gorgon, an interactive molecular modeling system
