# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jordan/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jordan/source

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jordan/source/CMakeFiles /home/jordan/source/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jordan/source/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pyGORGON

# Build rule for target.
pyGORGON: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pyGORGON
.PHONY : pyGORGON

# fast build rule for target.
pyGORGON/fast:
	$(MAKE) -f CMakeFiles/pyGORGON.dir/build.make CMakeFiles/pyGORGON.dir/build
.PHONY : pyGORGON/fast

# Manual pre-install relink rule for target.
pyGORGON/preinstall:
	$(MAKE) -f CMakeFiles/pyGORGON.dir/build.make CMakeFiles/pyGORGON.dir/preinstall
.PHONY : pyGORGON/preinstall

Gorgon/src_cpp/LibPyGorgon.o: Gorgon/src_cpp/LibPyGorgon.cpp.o
.PHONY : Gorgon/src_cpp/LibPyGorgon.o

# target to build an object file
Gorgon/src_cpp/LibPyGorgon.cpp.o:
	$(MAKE) -f CMakeFiles/pyGORGON.dir/build.make CMakeFiles/pyGORGON.dir/Gorgon/src_cpp/LibPyGorgon.cpp.o
.PHONY : Gorgon/src_cpp/LibPyGorgon.cpp.o

Gorgon/src_cpp/LibPyGorgon.i: Gorgon/src_cpp/LibPyGorgon.cpp.i
.PHONY : Gorgon/src_cpp/LibPyGorgon.i

# target to preprocess a source file
Gorgon/src_cpp/LibPyGorgon.cpp.i:
	$(MAKE) -f CMakeFiles/pyGORGON.dir/build.make CMakeFiles/pyGORGON.dir/Gorgon/src_cpp/LibPyGorgon.cpp.i
.PHONY : Gorgon/src_cpp/LibPyGorgon.cpp.i

Gorgon/src_cpp/LibPyGorgon.s: Gorgon/src_cpp/LibPyGorgon.cpp.s
.PHONY : Gorgon/src_cpp/LibPyGorgon.s

# target to generate assembly for a file
Gorgon/src_cpp/LibPyGorgon.cpp.s:
	$(MAKE) -f CMakeFiles/pyGORGON.dir/build.make CMakeFiles/pyGORGON.dir/Gorgon/src_cpp/LibPyGorgon.cpp.s
.PHONY : Gorgon/src_cpp/LibPyGorgon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... pyGORGON"
	@echo "... rebuild_cache"
	@echo "... Gorgon/src_cpp/LibPyGorgon.o"
	@echo "... Gorgon/src_cpp/LibPyGorgon.i"
	@echo "... Gorgon/src_cpp/LibPyGorgon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

