"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gorgon.pyw']
DATA_FILES = [('', ['splash.png', 'gorgon.icns']),
	('../../../themes', ['../resources/Dark.thm', '../resources/Light.thm'] )]
OPTIONS = {'argv_emulation': True,
	   'iconfile' : 'gorgon.icns',
	   'packages' : [],
	   "includes" : ['sip', 'PyQt4'],
	   "excludes" : []
	   }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
