# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += VolumeFileTypes


# Input

INCLUDEPATH += ../ByteOrder
INCLUDEPATH += ..

SOURCES =  \
		DXFile.cpp \
		MRCFile.cpp \
		RawIVFile.cpp \
		RawVFile.cpp \
		VolumeFileType.cpp \
		VolumeLoader.cpp

HEADERS =  \
		DXFile.h \
		MRCFile.h \
		RawIVFile.h \
		RawVFile.h \
		VolumeFileType.h \
		VolumeLoader.h 


