# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src_ui/ui_dialog_volume_sse_builder.ui'
#
# Created: Thu Jul  8 16:24:01 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogVolumeSSEBuilder(object):
    def setupUi(self, DialogVolumeSSEBuilder):
        DialogVolumeSSEBuilder.setObjectName("DialogVolumeSSEBuilder")
        DialogVolumeSSEBuilder.resize(361, 553)
        self.gridLayout_2 = QtGui.QGridLayout(DialogVolumeSSEBuilder)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelAtomScore = QtGui.QLabel(DialogVolumeSSEBuilder)
        self.labelAtomScore.setObjectName("labelAtomScore")
        self.gridLayout_2.addWidget(self.labelAtomScore, 0, 0, 1, 2)
        self.tabWidgetScoredAtoms = QtGui.QTabWidget(DialogVolumeSSEBuilder)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetScoredAtoms.sizePolicy().hasHeightForWidth())
        self.tabWidgetScoredAtoms.setSizePolicy(sizePolicy)
        self.tabWidgetScoredAtoms.setObjectName("tabWidgetScoredAtoms")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButtonLoadVolume = QtGui.QPushButton(self.tab)
        self.pushButtonLoadVolume.setObjectName("pushButtonLoadVolume")
        self.hboxlayout.addWidget(self.pushButtonLoadVolume)
        self.pushButtonLoadSkeleton = QtGui.QPushButton(self.tab)
        self.pushButtonLoadSkeleton.setObjectName("pushButtonLoadSkeleton")
        self.hboxlayout.addWidget(self.pushButtonLoadSkeleton)
        self.gridLayout.addLayout(self.hboxlayout, 0, 0, 1, 3)
        self.labelThreshold = QtGui.QLabel(self.tab)
        self.labelThreshold.setEnabled(False)
        self.labelThreshold.setObjectName("labelThreshold")
        self.gridLayout.addWidget(self.labelThreshold, 1, 0, 1, 2)
        self.doubleSpinBoxThreshold = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxThreshold.setEnabled(False)
        self.doubleSpinBoxThreshold.setMinimum(-100.0)
        self.doubleSpinBoxThreshold.setMaximum(100.0)
        self.doubleSpinBoxThreshold.setProperty("value", 0.38)
        self.doubleSpinBoxThreshold.setObjectName("doubleSpinBoxThreshold")
        self.gridLayout.addWidget(self.doubleSpinBoxThreshold, 1, 2, 1, 1)
        self.labelVolumeResolution = QtGui.QLabel(self.tab)
        self.labelVolumeResolution.setEnabled(False)
        self.labelVolumeResolution.setObjectName("labelVolumeResolution")
        self.gridLayout.addWidget(self.labelVolumeResolution, 2, 0, 1, 2)
        self.doubleSpinBoxResolution = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxResolution.setEnabled(False)
        self.doubleSpinBoxResolution.setMaximum(1000.0)
        self.doubleSpinBoxResolution.setProperty("value", 8.0)
        self.doubleSpinBoxResolution.setObjectName("doubleSpinBoxResolution")
        self.gridLayout.addWidget(self.doubleSpinBoxResolution, 2, 2, 1, 1)
        self.labelSkeletonScore = QtGui.QLabel(self.tab)
        self.labelSkeletonScore.setEnabled(False)
        self.labelSkeletonScore.setObjectName("labelSkeletonScore")
        self.gridLayout.addWidget(self.labelSkeletonScore, 3, 0, 1, 2)
        self.doubleSpinBoxSkeleton = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxSkeleton.setEnabled(False)
        self.doubleSpinBoxSkeleton.setMaximum(1.0)
        self.doubleSpinBoxSkeleton.setProperty("value", 1.0)
        self.doubleSpinBoxSkeleton.setObjectName("doubleSpinBoxSkeleton")
        self.gridLayout.addWidget(self.doubleSpinBoxSkeleton, 3, 2, 1, 1)
        self.labelCrossCorrelationScore = QtGui.QLabel(self.tab)
        self.labelCrossCorrelationScore.setEnabled(False)
        self.labelCrossCorrelationScore.setObjectName("labelCrossCorrelationScore")
        self.gridLayout.addWidget(self.labelCrossCorrelationScore, 4, 0, 1, 2)
        self.doubleSpinBoxCorrelation = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxCorrelation.setEnabled(False)
        self.doubleSpinBoxCorrelation.setMaximum(1.0)
        self.doubleSpinBoxCorrelation.setProperty("value", 1.0)
        self.doubleSpinBoxCorrelation.setObjectName("doubleSpinBoxCorrelation")
        self.gridLayout.addWidget(self.doubleSpinBoxCorrelation, 4, 2, 1, 1)
        self.labelGeometricScore = QtGui.QLabel(self.tab)
        self.labelGeometricScore.setEnabled(False)
        self.labelGeometricScore.setObjectName("labelGeometricScore")
        self.gridLayout.addWidget(self.labelGeometricScore, 5, 0, 1, 2)
        self.doubleSpinBoxGeometry = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxGeometry.setEnabled(False)
        self.doubleSpinBoxGeometry.setMaximum(1.0)
        self.doubleSpinBoxGeometry.setProperty("value", 1.0)
        self.doubleSpinBoxGeometry.setObjectName("doubleSpinBoxGeometry")
        self.gridLayout.addWidget(self.doubleSpinBoxGeometry, 5, 2, 1, 1)
        self.pushButtonSSEHunter = QtGui.QPushButton(self.tab)
        self.pushButtonSSEHunter.setEnabled(False)
        self.pushButtonSSEHunter.setObjectName("pushButtonSSEHunter")
        self.gridLayout.addWidget(self.pushButtonSSEHunter, 6, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(134, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.pushButtonSavePseudoatoms = QtGui.QPushButton(self.tab)
        self.pushButtonSavePseudoatoms.setEnabled(False)
        self.pushButtonSavePseudoatoms.setObjectName("pushButtonSavePseudoatoms")
        self.gridLayout.addWidget(self.pushButtonSavePseudoatoms, 7, 1, 1, 2)
        self.tabWidgetScoredAtoms.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridlayout = QtGui.QGridLayout(self.tab_2)
        self.gridlayout.setObjectName("gridlayout")
        self.labelAtomScore_2 = QtGui.QLabel(self.tab_2)
        self.labelAtomScore_2.setObjectName("labelAtomScore_2")
        self.gridlayout.addWidget(self.labelAtomScore_2, 0, 0, 1, 1)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName("gridlayout1")
        self.lineEditAtomScore = QtGui.QLineEdit(self.tab_2)
        self.lineEditAtomScore.setReadOnly(True)
        self.lineEditAtomScore.setObjectName("lineEditAtomScore")
        self.gridlayout1.addWidget(self.lineEditAtomScore, 0, 0, 1, 1)
        self.pushButtonBrowseAtomScore = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBrowseAtomScore.sizePolicy().hasHeightForWidth())
        self.pushButtonBrowseAtomScore.setSizePolicy(sizePolicy)
        self.pushButtonBrowseAtomScore.setObjectName("pushButtonBrowseAtomScore")
        self.gridlayout1.addWidget(self.pushButtonBrowseAtomScore, 0, 1, 1, 1)
        self.gridlayout.addLayout(self.gridlayout1, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.tabWidgetScoredAtoms.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidgetScoredAtoms, 1, 0, 1, 3)
        self.line = QtGui.QFrame(DialogVolumeSSEBuilder)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 3)
        self.tabWidgetAddSSEs = QtGui.QTabWidget(DialogVolumeSSEBuilder)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetAddSSEs.sizePolicy().hasHeightForWidth())
        self.tabWidgetAddSSEs.setSizePolicy(sizePolicy)
        self.tabWidgetAddSSEs.setObjectName("tabWidgetAddSSEs")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelSelection = QtGui.QLabel(self.tab_3)
        self.labelSelection.setObjectName("labelSelection")
        self.verticalLayout.addWidget(self.labelSelection)
        self.tableWidgetSelection = QtGui.QTableWidget(self.tab_3)
        self.tableWidgetSelection.setEnabled(False)
        self.tableWidgetSelection.setAlternatingRowColors(True)
        self.tableWidgetSelection.setObjectName("tableWidgetSelection")
        self.tableWidgetSelection.setColumnCount(2)
        self.tableWidgetSelection.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSelection.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSelection.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidgetSelection)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonRemoveSSE = QtGui.QPushButton(self.tab_3)
        self.pushButtonRemoveSSE.setObjectName("pushButtonRemoveSSE")
        self.horizontalLayout.addWidget(self.pushButtonRemoveSSE)
        spacerItem2 = QtGui.QSpacerItem(306, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonSelectionToSheet = QtGui.QPushButton(self.tab_3)
        self.pushButtonSelectionToSheet.setObjectName("pushButtonSelectionToSheet")
        self.horizontalLayout.addWidget(self.pushButtonSelectionToSheet)
        self.pushButtonSelectionToHelix = QtGui.QPushButton(self.tab_3)
        self.pushButtonSelectionToHelix.setObjectName("pushButtonSelectionToHelix")
        self.horizontalLayout.addWidget(self.pushButtonSelectionToHelix)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidgetAddSSEs.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget = QtGui.QWidget(self.tab_4)
        self.widget.setGeometry(QtCore.QRect(0, 0, 281, 102))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalSliderLinearityThresh = QtGui.QSlider(self.widget)
        self.horizontalSliderLinearityThresh.setMinimum(0)
        self.horizontalSliderLinearityThresh.setMaximum(10)
        self.horizontalSliderLinearityThresh.setProperty("value", 5)
        self.horizontalSliderLinearityThresh.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderLinearityThresh.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.horizontalSliderLinearityThresh.setTickInterval(1)
        self.horizontalSliderLinearityThresh.setObjectName("horizontalSliderLinearityThresh")
        self.horizontalLayout_2.addWidget(self.horizontalSliderLinearityThresh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.doubleSpinBoxScoreThresh = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxScoreThresh.setMinimum(-3.0)
        self.doubleSpinBoxScoreThresh.setMaximum(3.0)
        self.doubleSpinBoxScoreThresh.setSingleStep(0.1)
        self.doubleSpinBoxScoreThresh.setObjectName("doubleSpinBoxScoreThresh")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxScoreThresh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonRemoveHelices = QtGui.QPushButton(self.widget)
        self.pushButtonRemoveHelices.setObjectName("pushButtonRemoveHelices")
        self.horizontalLayout_4.addWidget(self.pushButtonRemoveHelices)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButtonAddHelices = QtGui.QPushButton(self.widget)
        self.pushButtonAddHelices.setObjectName("pushButtonAddHelices")
        self.horizontalLayout_4.addWidget(self.pushButtonAddHelices)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidgetAddSSEs.addTab(self.tab_4, "")
        self.gridLayout_2.addWidget(self.tabWidgetAddSSEs, 3, 0, 1, 1)

        self.retranslateUi(DialogVolumeSSEBuilder)
        self.tabWidgetScoredAtoms.setCurrentIndex(0)
        self.tabWidgetAddSSEs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogVolumeSSEBuilder)
        DialogVolumeSSEBuilder.setTabOrder(self.tabWidgetScoredAtoms, self.pushButtonLoadVolume)
        DialogVolumeSSEBuilder.setTabOrder(self.pushButtonLoadVolume, self.pushButtonLoadSkeleton)
        DialogVolumeSSEBuilder.setTabOrder(self.pushButtonLoadSkeleton, self.doubleSpinBoxThreshold)
        DialogVolumeSSEBuilder.setTabOrder(self.doubleSpinBoxThreshold, self.doubleSpinBoxResolution)
        DialogVolumeSSEBuilder.setTabOrder(self.doubleSpinBoxResolution, self.doubleSpinBoxSkeleton)
        DialogVolumeSSEBuilder.setTabOrder(self.doubleSpinBoxSkeleton, self.doubleSpinBoxCorrelation)
        DialogVolumeSSEBuilder.setTabOrder(self.doubleSpinBoxCorrelation, self.doubleSpinBoxGeometry)
        DialogVolumeSSEBuilder.setTabOrder(self.doubleSpinBoxGeometry, self.pushButtonSSEHunter)
        DialogVolumeSSEBuilder.setTabOrder(self.pushButtonSSEHunter, self.pushButtonSavePseudoatoms)
        DialogVolumeSSEBuilder.setTabOrder(self.pushButtonSavePseudoatoms, self.lineEditAtomScore)
        DialogVolumeSSEBuilder.setTabOrder(self.lineEditAtomScore, self.pushButtonBrowseAtomScore)

    def retranslateUi(self, DialogVolumeSSEBuilder):
        DialogVolumeSSEBuilder.setWindowTitle(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "SSE Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAtomScore.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Scored Pseudoatoms:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoadVolume.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Load Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoadSkeleton.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Load Skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelThreshold.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVolumeResolution.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Volume Resolution (A):", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSkeletonScore.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Skeleton Influence:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCrossCorrelationScore.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Helix Correlation Influence:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGeometricScore.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Geometric Influence:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSSEHunter.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Find Scored Pseudoatoms (SSEHunter)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSavePseudoatoms.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Save Pseudoatoms", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetScoredAtoms.setTabText(self.tabWidgetScoredAtoms.indexOf(self.tab), QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Calculate using SSEHunter", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAtomScore_2.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Scored Pseudoatom File:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseAtomScore.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetScoredAtoms.setTabText(self.tabWidgetScoredAtoms.indexOf(self.tab_2), QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Load from file", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelection.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Atom Selection:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSelection.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSelection.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "SSE Hunter Score", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRemoveSSE.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Remove SSE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelectionToSheet.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Add Sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelectionToHelix.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Add Helix", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetAddSSEs.setTabText(self.tabWidgetAddSSEs.indexOf(self.tab_3), QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Linearity Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Score Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRemoveHelices.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Remove All", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddHelices.setText(QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Add Helices", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetAddSSEs.setTabText(self.tabWidgetAddSSEs.indexOf(self.tab_4), QtGui.QApplication.translate("DialogVolumeSSEBuilder", "Auto Helix", None, QtGui.QApplication.UnicodeUTF8))

