# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_volume_surface_editor.ui'
#
# Created: Sun Jan 17 12:22:25 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogVolumeSurfaceEditor(object):
    def setupUi(self, DialogVolumeSurfaceEditor):
        DialogVolumeSurfaceEditor.setObjectName("DialogVolumeSurfaceEditor")
        DialogVolumeSurfaceEditor.resize(579, 124)
        DialogVolumeSurfaceEditor.setMinimumSize(QtCore.QSize(230, 124))
        self.verticalLayout = QtGui.QVBoxLayout(DialogVolumeSurfaceEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonIsoSurface = QtGui.QRadioButton(DialogVolumeSurfaceEditor)
        self.radioButtonIsoSurface.setChecked(True)
        self.radioButtonIsoSurface.setObjectName("radioButtonIsoSurface")
        self.horizontalLayout_3.addWidget(self.radioButtonIsoSurface)
        self.radioButtonCrossSection = QtGui.QRadioButton(DialogVolumeSurfaceEditor)
        self.radioButtonCrossSection.setObjectName("radioButtonCrossSection")
        self.horizontalLayout_3.addWidget(self.radioButtonCrossSection)
        self.radioButtonSolid = QtGui.QRadioButton(DialogVolumeSurfaceEditor)
        self.radioButtonSolid.setObjectName("radioButtonSolid")
        self.horizontalLayout_3.addWidget(self.radioButtonSolid)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.histogram = HistogramSliderWidget(DialogVolumeSurfaceEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        self.histogram.setMinimumSize(QtCore.QSize(20, 40))
        self.histogram.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.histogram.setObjectName("histogram")
        self.verticalLayout.addWidget(self.histogram)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelIsoLevel = QtGui.QLabel(DialogVolumeSurfaceEditor)
        self.labelIsoLevel.setObjectName("labelIsoLevel")
        self.horizontalLayout.addWidget(self.labelIsoLevel)
        self.doubleSpinBoxDensity = QtGui.QDoubleSpinBox(DialogVolumeSurfaceEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxDensity.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxDensity.setSizePolicy(sizePolicy)
        self.doubleSpinBoxDensity.setDecimals(3)
        self.doubleSpinBoxDensity.setMaximum(25500.0)
        self.doubleSpinBoxDensity.setObjectName("doubleSpinBoxDensity")
        self.horizontalLayout.addWidget(self.doubleSpinBoxDensity)
        self.labelIsoLevelMax = QtGui.QLabel(DialogVolumeSurfaceEditor)
        self.labelIsoLevelMax.setObjectName("labelIsoLevelMax")
        self.horizontalLayout.addWidget(self.labelIsoLevelMax)
        self.doubleSpinBoxDensityMax = QtGui.QDoubleSpinBox(DialogVolumeSurfaceEditor)
        self.doubleSpinBoxDensityMax.setDecimals(3)
        self.doubleSpinBoxDensityMax.setMaximum(25500.0)
        self.doubleSpinBoxDensityMax.setObjectName("doubleSpinBoxDensityMax")
        self.horizontalLayout.addWidget(self.doubleSpinBoxDensityMax)
        self.labelSamplingInterval = QtGui.QLabel(DialogVolumeSurfaceEditor)
        self.labelSamplingInterval.setObjectName("labelSamplingInterval")
        self.horizontalLayout.addWidget(self.labelSamplingInterval)
        self.comboBoxSamplingInterval = QtGui.QComboBox(DialogVolumeSurfaceEditor)
        self.comboBoxSamplingInterval.setObjectName("comboBoxSamplingInterval")
        self.comboBoxSamplingInterval.addItem(QtCore.QString())
        self.comboBoxSamplingInterval.addItem(QtCore.QString())
        self.comboBoxSamplingInterval.addItem(QtCore.QString())
        self.comboBoxSamplingInterval.addItem(QtCore.QString())
        self.comboBoxSamplingInterval.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.comboBoxSamplingInterval)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxUseRadius = QtGui.QCheckBox(DialogVolumeSurfaceEditor)
        self.checkBoxUseRadius.setObjectName("checkBoxUseRadius")
        self.horizontalLayout_2.addWidget(self.checkBoxUseRadius)
        self.horizontalSliderDisplayRadius = QtGui.QSlider(DialogVolumeSurfaceEditor)
        self.horizontalSliderDisplayRadius.setEnabled(False)
        self.horizontalSliderDisplayRadius.setMinimum(1)
        self.horizontalSliderDisplayRadius.setMaximum(255)
        self.horizontalSliderDisplayRadius.setPageStep(1)
        self.horizontalSliderDisplayRadius.setProperty("value", QtCore.QVariant(255))
        self.horizontalSliderDisplayRadius.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderDisplayRadius.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSliderDisplayRadius.setTickInterval(0)
        self.horizontalSliderDisplayRadius.setObjectName("horizontalSliderDisplayRadius")
        self.horizontalLayout_2.addWidget(self.horizontalSliderDisplayRadius)
        self.labelDisplayRadiusDisplay = QtGui.QLabel(DialogVolumeSurfaceEditor)
        self.labelDisplayRadiusDisplay.setEnabled(False)
        self.labelDisplayRadiusDisplay.setObjectName("labelDisplayRadiusDisplay")
        self.horizontalLayout_2.addWidget(self.labelDisplayRadiusDisplay)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DialogVolumeSurfaceEditor)
        QtCore.QObject.connect(self.radioButtonIsoSurface, QtCore.SIGNAL("toggled(bool)"), self.labelSamplingInterval.setVisible)
        QtCore.QObject.connect(self.horizontalSliderDisplayRadius, QtCore.SIGNAL("valueChanged(int)"), self.labelDisplayRadiusDisplay.setNum)
        QtCore.QObject.connect(self.radioButtonIsoSurface, QtCore.SIGNAL("toggled(bool)"), self.horizontalSliderDisplayRadius.setVisible)
        QtCore.QObject.connect(self.radioButtonIsoSurface, QtCore.SIGNAL("toggled(bool)"), self.labelDisplayRadiusDisplay.setVisible)
        QtCore.QObject.connect(self.radioButtonIsoSurface, QtCore.SIGNAL("toggled(bool)"), self.labelIsoLevelMax.setHidden)
        QtCore.QObject.connect(self.radioButtonIsoSurface, QtCore.SIGNAL("toggled(bool)"), self.doubleSpinBoxDensityMax.setHidden)
        QtCore.QObject.connect(self.checkBoxUseRadius, QtCore.SIGNAL("toggled(bool)"), self.horizontalSliderDisplayRadius.setEnabled)
        QtCore.QObject.connect(self.checkBoxUseRadius, QtCore.SIGNAL("toggled(bool)"), self.labelDisplayRadiusDisplay.setEnabled)
        QtCore.QObject.connect(self.radioButtonIsoSurface, QtCore.SIGNAL("toggled(bool)"), self.checkBoxUseRadius.setVisible)
        QtCore.QObject.connect(self.radioButtonIsoSurface, QtCore.SIGNAL("toggled(bool)"), self.comboBoxSamplingInterval.setVisible)
        QtCore.QMetaObject.connectSlotsByName(DialogVolumeSurfaceEditor)
        DialogVolumeSurfaceEditor.setTabOrder(self.radioButtonIsoSurface, self.radioButtonCrossSection)
        DialogVolumeSurfaceEditor.setTabOrder(self.radioButtonCrossSection, self.radioButtonSolid)
        DialogVolumeSurfaceEditor.setTabOrder(self.radioButtonSolid, self.doubleSpinBoxDensity)
        DialogVolumeSurfaceEditor.setTabOrder(self.doubleSpinBoxDensity, self.doubleSpinBoxDensityMax)
        DialogVolumeSurfaceEditor.setTabOrder(self.doubleSpinBoxDensityMax, self.comboBoxSamplingInterval)
        DialogVolumeSurfaceEditor.setTabOrder(self.comboBoxSamplingInterval, self.checkBoxUseRadius)
        DialogVolumeSurfaceEditor.setTabOrder(self.checkBoxUseRadius, self.horizontalSliderDisplayRadius)

    def retranslateUi(self, DialogVolumeSurfaceEditor):
        DialogVolumeSurfaceEditor.setWindowTitle(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Volume - Surface Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonIsoSurface.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Display volume as an Iso Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonIsoSurface.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Display volume as an Iso Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonIsoSurface.setText(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Iso-surface view", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCrossSection.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Display the volume as a cross-section", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCrossSection.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Display the volume as a cross-section", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCrossSection.setText(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Cross-Section view", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSolid.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Display volume as a solid volumetric rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSolid.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Display volume as a solid volumetric rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSolid.setText(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Solid view", None, QtGui.QApplication.UnicodeUTF8))
        self.histogram.setStatusTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Volume density histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.histogram.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "A histogram showing the distribution of density values in the volume.", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIsoLevel.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "The currently selected density of the volume", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIsoLevel.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "The currently selected density of the volume", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIsoLevel.setText(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Density:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxDensity.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "The currently selected density of the volume", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxDensity.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "The currently selected density of the volume", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIsoLevelMax.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Maximum density to be shown in solid rendering mode", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIsoLevelMax.setText(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Maximum Density:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxDensityMax.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Maximum density to be shown in solid rendering mode", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxDensityMax.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Maximum density to be shown in solid rendering mode", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSamplingInterval.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", " Sampling rate of the density.", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSamplingInterval.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Sampling rate of the density.", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSamplingInterval.setText(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Sampling Interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSamplingInterval.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", " Sampling rate of the density.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSamplingInterval.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Sampling rate of the density.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSamplingInterval.setItemText(0, QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSamplingInterval.setItemText(1, QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSamplingInterval.setItemText(2, QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSamplingInterval.setItemText(3, QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSamplingInterval.setItemText(4, QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseRadius.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "The volume will be displayed for this radius around the selected point", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseRadius.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "The volume will be displayed for this radius around the selected point", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseRadius.setText(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "Display Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalSliderDisplayRadius.setToolTip(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "The volume will be displayed for this radius around the selected point", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalSliderDisplayRadius.setWhatsThis(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "The volume will be displayed for this radius around the selected point", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDisplayRadiusDisplay.setText(QtGui.QApplication.translate("DialogVolumeSurfaceEditor", "255", None, QtGui.QApplication.UnicodeUTF8))

from histogram_slider_widget import HistogramSliderWidget
