# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_calpha_flexible_fitting.ui'
#
# Created: Mon Dec 15 16:11:21 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogCAlphaFlexibleFitting(object):
    def setupUi(self, DialogCAlphaFlexibleFitting):
        DialogCAlphaFlexibleFitting.setObjectName(_fromUtf8("DialogCAlphaFlexibleFitting"))
        DialogCAlphaFlexibleFitting.resize(405, 605)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogCAlphaFlexibleFitting.sizePolicy().hasHeightForWidth())
        DialogCAlphaFlexibleFitting.setSizePolicy(sizePolicy)
        DialogCAlphaFlexibleFitting.setMinimumSize(QtCore.QSize(270, 296))
        self.verticalLayout_3 = QtGui.QVBoxLayout(DialogCAlphaFlexibleFitting)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonLoadHelices = QtGui.QPushButton(DialogCAlphaFlexibleFitting)
        self.pushButtonLoadHelices.setObjectName(_fromUtf8("pushButtonLoadHelices"))
        self.horizontalLayout.addWidget(self.pushButtonLoadHelices)
        self.pushButtonLoadCAlpha = QtGui.QPushButton(DialogCAlphaFlexibleFitting)
        self.pushButtonLoadCAlpha.setObjectName(_fromUtf8("pushButtonLoadCAlpha"))
        self.horizontalLayout.addWidget(self.pushButtonLoadCAlpha)
        self.pushButtonLoadReference = QtGui.QPushButton(DialogCAlphaFlexibleFitting)
        self.pushButtonLoadReference.setObjectName(_fromUtf8("pushButtonLoadReference"))
        self.horizontalLayout.addWidget(self.pushButtonLoadReference)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(DialogCAlphaFlexibleFitting)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRigid = QtGui.QWidget()
        self.tabRigid.setObjectName(_fromUtf8("tabRigid"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabRigid)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelCandidateCount = QtGui.QLabel(self.tabRigid)
        self.labelCandidateCount.setObjectName(_fromUtf8("labelCandidateCount"))
        self.horizontalLayout_8.addWidget(self.labelCandidateCount)
        self.spinBoxMaxAlignments = QtGui.QSpinBox(self.tabRigid)
        self.spinBoxMaxAlignments.setSuffix(_fromUtf8(""))
        self.spinBoxMaxAlignments.setMinimum(1)
        self.spinBoxMaxAlignments.setMaximum(100)
        self.spinBoxMaxAlignments.setProperty("value", 5)
        self.spinBoxMaxAlignments.setObjectName(_fromUtf8("spinBoxMaxAlignments"))
        self.horizontalLayout_8.addWidget(self.spinBoxMaxAlignments)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.groupBoxAdvancedSettings = QtGui.QGroupBox(self.tabRigid)
        self.groupBoxAdvancedSettings.setObjectName(_fromUtf8("groupBoxAdvancedSettings"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBoxAdvancedSettings)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelJointAngleThreshold_4 = QtGui.QLabel(self.groupBoxAdvancedSettings)
        self.labelJointAngleThreshold_4.setToolTip(_fromUtf8(""))
        self.labelJointAngleThreshold_4.setObjectName(_fromUtf8("labelJointAngleThreshold_4"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelJointAngleThreshold_4)
        self.spinBoxJointAngleThreshold = QtGui.QSpinBox(self.groupBoxAdvancedSettings)
        self.spinBoxJointAngleThreshold.setMaximum(180)
        self.spinBoxJointAngleThreshold.setProperty("value", 30)
        self.spinBoxJointAngleThreshold.setObjectName(_fromUtf8("spinBoxJointAngleThreshold"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxJointAngleThreshold)
        self.labelJointAngleThreshold_3 = QtGui.QLabel(self.groupBoxAdvancedSettings)
        self.labelJointAngleThreshold_3.setToolTip(_fromUtf8(""))
        self.labelJointAngleThreshold_3.setObjectName(_fromUtf8("labelJointAngleThreshold_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelJointAngleThreshold_3)
        self.spinBoxDihedralAngleThreshold = QtGui.QSpinBox(self.groupBoxAdvancedSettings)
        self.spinBoxDihedralAngleThreshold.setMaximum(180)
        self.spinBoxDihedralAngleThreshold.setProperty("value", 30)
        self.spinBoxDihedralAngleThreshold.setObjectName(_fromUtf8("spinBoxDihedralAngleThreshold"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxDihedralAngleThreshold)
        self.labelJointAngleThreshold_2 = QtGui.QLabel(self.groupBoxAdvancedSettings)
        self.labelJointAngleThreshold_2.setToolTip(_fromUtf8(""))
        self.labelJointAngleThreshold_2.setObjectName(_fromUtf8("labelJointAngleThreshold_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelJointAngleThreshold_2)
        self.spinBoxHelixLengthThreshold = QtGui.QSpinBox(self.groupBoxAdvancedSettings)
        self.spinBoxHelixLengthThreshold.setMaximum(50)
        self.spinBoxHelixLengthThreshold.setProperty("value", 10)
        self.spinBoxHelixLengthThreshold.setObjectName(_fromUtf8("spinBoxHelixLengthThreshold"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxHelixLengthThreshold)
        self.labelJointAngleThreshold = QtGui.QLabel(self.groupBoxAdvancedSettings)
        self.labelJointAngleThreshold.setObjectName(_fromUtf8("labelJointAngleThreshold"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelJointAngleThreshold)
        self.spinBoxHelixCentroidThreshold = QtGui.QSpinBox(self.groupBoxAdvancedSettings)
        self.spinBoxHelixCentroidThreshold.setMaximum(50)
        self.spinBoxHelixCentroidThreshold.setProperty("value", 5)
        self.spinBoxHelixCentroidThreshold.setObjectName(_fromUtf8("spinBoxHelixCentroidThreshold"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxHelixCentroidThreshold)
        self.verticalLayout_6.addWidget(self.groupBoxAdvancedSettings)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(358, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonReset = QtGui.QPushButton(self.tabRigid)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.horizontalLayout_3.addWidget(self.pushButtonReset)
        self.pushButtonOk = QtGui.QPushButton(self.tabRigid)
        self.pushButtonOk.setObjectName(_fromUtf8("pushButtonOk"))
        self.horizontalLayout_3.addWidget(self.pushButtonOk)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabRigid, _fromUtf8(""))
        self.tabAlignments = QtGui.QWidget()
        self.tabAlignments.setObjectName(_fromUtf8("tabAlignments"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabAlignments)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelAlignment = QtGui.QLabel(self.tabAlignments)
        self.labelAlignment.setObjectName(_fromUtf8("labelAlignment"))
        self.horizontalLayout_5.addWidget(self.labelAlignment)
        self.comboBoxAlignment = QtGui.QComboBox(self.tabAlignments)
        self.comboBoxAlignment.setObjectName(_fromUtf8("comboBoxAlignment"))
        self.horizontalLayout_5.addWidget(self.comboBoxAlignment)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtGui.QTableWidget(self.tabAlignments)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.widget_2 = QtGui.QWidget(self.tabAlignments)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBoxCluster = QtGui.QComboBox(self.widget_2)
        self.comboBoxCluster.setObjectName(_fromUtf8("comboBoxCluster"))
        self.horizontalLayout_4.addWidget(self.comboBoxCluster)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.groupBoxHelixMatching = QtGui.QGroupBox(self.tabAlignments)
        self.groupBoxHelixMatching.setObjectName(_fromUtf8("groupBoxHelixMatching"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxHelixMatching)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.groupBoxHelixMatching)
        self.label.setLineWidth(2)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.pushButtonMatchHelices = QtGui.QPushButton(self.groupBoxHelixMatching)
        self.pushButtonMatchHelices.setObjectName(_fromUtf8("pushButtonMatchHelices"))
        self.horizontalLayout_6.addWidget(self.pushButtonMatchHelices)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBoxHelixMatching)
        self.groupBoxClusterMerging = QtGui.QGroupBox(self.tabAlignments)
        self.groupBoxClusterMerging.setObjectName(_fromUtf8("groupBoxClusterMerging"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxClusterMerging)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBoxClusterMerging)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBoxMerge1 = QtGui.QComboBox(self.groupBoxClusterMerging)
        self.comboBoxMerge1.setObjectName(_fromUtf8("comboBoxMerge1"))
        self.gridLayout.addWidget(self.comboBoxMerge1, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxClusterMerging)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBoxMerge2 = QtGui.QComboBox(self.groupBoxClusterMerging)
        self.comboBoxMerge2.setObjectName(_fromUtf8("comboBoxMerge2"))
        self.gridLayout.addWidget(self.comboBoxMerge2, 1, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.pushButtonMergeClusters = QtGui.QPushButton(self.groupBoxClusterMerging)
        self.pushButtonMergeClusters.setObjectName(_fromUtf8("pushButtonMergeClusters"))
        self.horizontalLayout_7.addWidget(self.pushButtonMergeClusters)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBoxClusterMerging)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.tabWidget.addTab(self.tabAlignments, _fromUtf8(""))
        self.tabFlexibleFit = QtGui.QWidget()
        self.tabFlexibleFit.setObjectName(_fromUtf8("tabFlexibleFit"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabFlexibleFit)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButtonFlexibleFitting = QtGui.QRadioButton(self.tabFlexibleFit)
        self.radioButtonFlexibleFitting.setChecked(True)
        self.radioButtonFlexibleFitting.setObjectName(_fromUtf8("radioButtonFlexibleFitting"))
        self.horizontalLayout_2.addWidget(self.radioButtonFlexibleFitting)
        self.radioButtonInterpolation = QtGui.QRadioButton(self.tabFlexibleFit)
        self.radioButtonInterpolation.setObjectName(_fromUtf8("radioButtonInterpolation"))
        self.horizontalLayout_2.addWidget(self.radioButtonInterpolation)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBoxFlexibleSettings = QtGui.QGroupBox(self.tabFlexibleFit)
        self.groupBoxFlexibleSettings.setObjectName(_fromUtf8("groupBoxFlexibleSettings"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBoxFlexibleSettings)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.flexibleSettings = QtGui.QFormLayout()
        self.flexibleSettings.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flexibleSettings.setObjectName(_fromUtf8("flexibleSettings"))
        self.useSoftHandlesCheckBox = QtGui.QCheckBox(self.groupBoxFlexibleSettings)
        self.useSoftHandlesCheckBox.setChecked(True)
        self.useSoftHandlesCheckBox.setTristate(False)
        self.useSoftHandlesCheckBox.setObjectName(_fromUtf8("useSoftHandlesCheckBox"))
        self.flexibleSettings.setWidget(0, QtGui.QFormLayout.FieldRole, self.useSoftHandlesCheckBox)
        self.doRigidInitializationLabel = QtGui.QLabel(self.groupBoxFlexibleSettings)
        self.doRigidInitializationLabel.setObjectName(_fromUtf8("doRigidInitializationLabel"))
        self.flexibleSettings.setWidget(1, QtGui.QFormLayout.LabelRole, self.doRigidInitializationLabel)
        self.doRigidInitializationCheckBox = QtGui.QCheckBox(self.groupBoxFlexibleSettings)
        self.doRigidInitializationCheckBox.setChecked(True)
        self.doRigidInitializationCheckBox.setObjectName(_fromUtf8("doRigidInitializationCheckBox"))
        self.flexibleSettings.setWidget(1, QtGui.QFormLayout.FieldRole, self.doRigidInitializationCheckBox)
        self.neighborhoodSizeLabel = QtGui.QLabel(self.groupBoxFlexibleSettings)
        self.neighborhoodSizeLabel.setObjectName(_fromUtf8("neighborhoodSizeLabel"))
        self.flexibleSettings.setWidget(2, QtGui.QFormLayout.LabelRole, self.neighborhoodSizeLabel)
        self.neighborhoodSizeSpinBox = QtGui.QSpinBox(self.groupBoxFlexibleSettings)
        self.neighborhoodSizeSpinBox.setMinimum(2)
        self.neighborhoodSizeSpinBox.setProperty("value", 3)
        self.neighborhoodSizeSpinBox.setObjectName(_fromUtf8("neighborhoodSizeSpinBox"))
        self.flexibleSettings.setWidget(2, QtGui.QFormLayout.FieldRole, self.neighborhoodSizeSpinBox)
        self.laplacianWeightLabel = QtGui.QLabel(self.groupBoxFlexibleSettings)
        self.laplacianWeightLabel.setObjectName(_fromUtf8("laplacianWeightLabel"))
        self.flexibleSettings.setWidget(3, QtGui.QFormLayout.LabelRole, self.laplacianWeightLabel)
        self.laplacianWeightDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBoxFlexibleSettings)
        self.laplacianWeightDoubleSpinBox.setMaximum(2.0)
        self.laplacianWeightDoubleSpinBox.setSingleStep(0.01)
        self.laplacianWeightDoubleSpinBox.setProperty("value", 1.0)
        self.laplacianWeightDoubleSpinBox.setObjectName(_fromUtf8("laplacianWeightDoubleSpinBox"))
        self.flexibleSettings.setWidget(3, QtGui.QFormLayout.FieldRole, self.laplacianWeightDoubleSpinBox)
        self.hardHandleWeightLabel = QtGui.QLabel(self.groupBoxFlexibleSettings)
        self.hardHandleWeightLabel.setObjectName(_fromUtf8("hardHandleWeightLabel"))
        self.flexibleSettings.setWidget(4, QtGui.QFormLayout.LabelRole, self.hardHandleWeightLabel)
        self.hardHandleWeightDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBoxFlexibleSettings)
        self.hardHandleWeightDoubleSpinBox.setMaximum(2.0)
        self.hardHandleWeightDoubleSpinBox.setSingleStep(0.01)
        self.hardHandleWeightDoubleSpinBox.setProperty("value", 1.0)
        self.hardHandleWeightDoubleSpinBox.setObjectName(_fromUtf8("hardHandleWeightDoubleSpinBox"))
        self.flexibleSettings.setWidget(4, QtGui.QFormLayout.FieldRole, self.hardHandleWeightDoubleSpinBox)
        self.softHandleWeightLabel = QtGui.QLabel(self.groupBoxFlexibleSettings)
        self.softHandleWeightLabel.setObjectName(_fromUtf8("softHandleWeightLabel"))
        self.flexibleSettings.setWidget(5, QtGui.QFormLayout.LabelRole, self.softHandleWeightLabel)
        self.softHandleWeightDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBoxFlexibleSettings)
        self.softHandleWeightDoubleSpinBox.setMaximum(2.0)
        self.softHandleWeightDoubleSpinBox.setSingleStep(0.01)
        self.softHandleWeightDoubleSpinBox.setProperty("value", 0.05)
        self.softHandleWeightDoubleSpinBox.setObjectName(_fromUtf8("softHandleWeightDoubleSpinBox"))
        self.flexibleSettings.setWidget(5, QtGui.QFormLayout.FieldRole, self.softHandleWeightDoubleSpinBox)
        self.useSoftHandlesLabel = QtGui.QLabel(self.groupBoxFlexibleSettings)
        self.useSoftHandlesLabel.setObjectName(_fromUtf8("useSoftHandlesLabel"))
        self.flexibleSettings.setWidget(0, QtGui.QFormLayout.LabelRole, self.useSoftHandlesLabel)
        self.verticalLayout_7.addLayout(self.flexibleSettings)
        self.verticalLayout.addWidget(self.groupBoxFlexibleSettings)
        self.widget = QtGui.QWidget(self.tabFlexibleFit)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.pushButtonRunFlexible = QtGui.QPushButton(self.widget)
        self.pushButtonRunFlexible.setObjectName(_fromUtf8("pushButtonRunFlexible"))
        self.horizontalLayout_15.addWidget(self.pushButtonRunFlexible)
        self.verticalLayout.addWidget(self.widget)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.tabWidget.addTab(self.tabFlexibleFit, _fromUtf8(""))
        self.tabValidation = QtGui.QWidget()
        self.tabValidation.setObjectName(_fromUtf8("tabValidation"))
        self.groupBoxValidationSettings = QtGui.QGroupBox(self.tabValidation)
        self.groupBoxValidationSettings.setGeometry(QtCore.QRect(10, 10, 365, 211))
        self.groupBoxValidationSettings.setObjectName(_fromUtf8("groupBoxValidationSettings"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBoxValidationSettings)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.validationSettings = QtGui.QFormLayout()
        self.validationSettings.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.validationSettings.setObjectName(_fromUtf8("validationSettings"))
        self.usePerfectMatchingLabel = QtGui.QLabel(self.groupBoxValidationSettings)
        self.usePerfectMatchingLabel.setObjectName(_fromUtf8("usePerfectMatchingLabel"))
        self.validationSettings.setWidget(0, QtGui.QFormLayout.LabelRole, self.usePerfectMatchingLabel)
        self.usePerfectMatchingCheckbox = QtGui.QCheckBox(self.groupBoxValidationSettings)
        self.usePerfectMatchingCheckbox.setChecked(True)
        self.usePerfectMatchingCheckbox.setTristate(False)
        self.usePerfectMatchingCheckbox.setObjectName(_fromUtf8("usePerfectMatchingCheckbox"))
        self.validationSettings.setWidget(0, QtGui.QFormLayout.FieldRole, self.usePerfectMatchingCheckbox)
        self.visualizePairwiseDistanceLabel = QtGui.QLabel(self.groupBoxValidationSettings)
        self.visualizePairwiseDistanceLabel.setObjectName(_fromUtf8("visualizePairwiseDistanceLabel"))
        self.validationSettings.setWidget(2, QtGui.QFormLayout.LabelRole, self.visualizePairwiseDistanceLabel)
        self.visualizePairwiseDistanceCheckbox = QtGui.QCheckBox(self.groupBoxValidationSettings)
        self.visualizePairwiseDistanceCheckbox.setText(_fromUtf8(""))
        self.visualizePairwiseDistanceCheckbox.setObjectName(_fromUtf8("visualizePairwiseDistanceCheckbox"))
        self.validationSettings.setWidget(2, QtGui.QFormLayout.FieldRole, self.visualizePairwiseDistanceCheckbox)
        self.farthestDistColorLabel = QtGui.QLabel(self.groupBoxValidationSettings)
        self.farthestDistColorLabel.setObjectName(_fromUtf8("farthestDistColorLabel"))
        self.validationSettings.setWidget(5, QtGui.QFormLayout.LabelRole, self.farthestDistColorLabel)
        self.pushButtonClosestColor = ColoredPushButton(self.groupBoxValidationSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClosestColor.sizePolicy().hasHeightForWidth())
        self.pushButtonClosestColor.setSizePolicy(sizePolicy)
        self.pushButtonClosestColor.setText(_fromUtf8(""))
        self.pushButtonClosestColor.setObjectName(_fromUtf8("pushButtonClosestColor"))
        self.validationSettings.setWidget(4, QtGui.QFormLayout.FieldRole, self.pushButtonClosestColor)
        self.pushButtonFarthestColor = ColoredPushButton(self.groupBoxValidationSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFarthestColor.sizePolicy().hasHeightForWidth())
        self.pushButtonFarthestColor.setSizePolicy(sizePolicy)
        self.pushButtonFarthestColor.setText(_fromUtf8(""))
        self.pushButtonFarthestColor.setObjectName(_fromUtf8("pushButtonFarthestColor"))
        self.validationSettings.setWidget(5, QtGui.QFormLayout.FieldRole, self.pushButtonFarthestColor)
        self.closestDistColorLabel = QtGui.QLabel(self.groupBoxValidationSettings)
        self.closestDistColorLabel.setObjectName(_fromUtf8("closestDistColorLabel"))
        self.validationSettings.setWidget(4, QtGui.QFormLayout.LabelRole, self.closestDistColorLabel)
        self.useHueColors = QtGui.QLabel(self.groupBoxValidationSettings)
        self.useHueColors.setObjectName(_fromUtf8("useHueColors"))
        self.validationSettings.setWidget(3, QtGui.QFormLayout.LabelRole, self.useHueColors)
        self.useHueColorsCheckbox = QtGui.QCheckBox(self.groupBoxValidationSettings)
        self.useHueColorsCheckbox.setText(_fromUtf8(""))
        self.useHueColorsCheckbox.setObjectName(_fromUtf8("useHueColorsCheckbox"))
        self.validationSettings.setWidget(3, QtGui.QFormLayout.FieldRole, self.useHueColorsCheckbox)
        self.verticalLayout_8.addLayout(self.validationSettings)
        self.groupBoxResults = QtGui.QGroupBox(self.tabValidation)
        self.groupBoxResults.setGeometry(QtCore.QRect(10, 220, 365, 91))
        self.groupBoxResults.setObjectName(_fromUtf8("groupBoxResults"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBoxResults)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.results = QtGui.QFormLayout()
        self.results.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.results.setObjectName(_fromUtf8("results"))
        self.showRMSDLabel = QtGui.QLabel(self.groupBoxResults)
        self.showRMSDLabel.setObjectName(_fromUtf8("showRMSDLabel"))
        self.results.setWidget(0, QtGui.QFormLayout.LabelRole, self.showRMSDLabel)
        self.showHausdorffLabel = QtGui.QLabel(self.groupBoxResults)
        self.showHausdorffLabel.setObjectName(_fromUtf8("showHausdorffLabel"))
        self.results.setWidget(1, QtGui.QFormLayout.LabelRole, self.showHausdorffLabel)
        self.showRMSDNum = QtGui.QLabel(self.groupBoxResults)
        self.showRMSDNum.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Ubuntu\";"))
        self.showRMSDNum.setFrameShape(QtGui.QFrame.StyledPanel)
        self.showRMSDNum.setText(_fromUtf8(""))
        self.showRMSDNum.setObjectName(_fromUtf8("showRMSDNum"))
        self.results.setWidget(0, QtGui.QFormLayout.FieldRole, self.showRMSDNum)
        self.showHasudorffNum = QtGui.QLabel(self.groupBoxResults)
        self.showHasudorffNum.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Ubuntu\";"))
        self.showHasudorffNum.setFrameShape(QtGui.QFrame.StyledPanel)
        self.showHasudorffNum.setText(_fromUtf8(""))
        self.showHasudorffNum.setObjectName(_fromUtf8("showHasudorffNum"))
        self.results.setWidget(1, QtGui.QFormLayout.FieldRole, self.showHasudorffNum)
        self.verticalLayout_9.addLayout(self.results)
        self.tabWidget.addTab(self.tabValidation, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(DialogCAlphaFlexibleFitting)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.pushButtonOk, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogCAlphaFlexibleFitting.accept)
        QtCore.QObject.connect(self.pushButtonReset, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogCAlphaFlexibleFitting.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogCAlphaFlexibleFitting)
        DialogCAlphaFlexibleFitting.setTabOrder(self.pushButtonLoadHelices, self.pushButtonLoadCAlpha)
        DialogCAlphaFlexibleFitting.setTabOrder(self.pushButtonLoadCAlpha, self.tabWidget)
        DialogCAlphaFlexibleFitting.setTabOrder(self.tabWidget, self.spinBoxMaxAlignments)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxMaxAlignments, self.spinBoxJointAngleThreshold)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxJointAngleThreshold, self.spinBoxDihedralAngleThreshold)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxDihedralAngleThreshold, self.spinBoxHelixLengthThreshold)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxHelixLengthThreshold, self.spinBoxHelixCentroidThreshold)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxHelixCentroidThreshold, self.pushButtonReset)
        DialogCAlphaFlexibleFitting.setTabOrder(self.pushButtonReset, self.pushButtonOk)
        DialogCAlphaFlexibleFitting.setTabOrder(self.pushButtonOk, self.comboBoxAlignment)
        DialogCAlphaFlexibleFitting.setTabOrder(self.comboBoxAlignment, self.tableWidget)
        DialogCAlphaFlexibleFitting.setTabOrder(self.tableWidget, self.comboBoxCluster)
        DialogCAlphaFlexibleFitting.setTabOrder(self.comboBoxCluster, self.pushButtonMatchHelices)
        DialogCAlphaFlexibleFitting.setTabOrder(self.pushButtonMatchHelices, self.radioButtonFlexibleFitting)
        DialogCAlphaFlexibleFitting.setTabOrder(self.radioButtonFlexibleFitting, self.radioButtonInterpolation)
        DialogCAlphaFlexibleFitting.setTabOrder(self.radioButtonInterpolation, self.useSoftHandlesCheckBox)
        DialogCAlphaFlexibleFitting.setTabOrder(self.useSoftHandlesCheckBox, self.doRigidInitializationCheckBox)
        DialogCAlphaFlexibleFitting.setTabOrder(self.doRigidInitializationCheckBox, self.neighborhoodSizeSpinBox)
        DialogCAlphaFlexibleFitting.setTabOrder(self.neighborhoodSizeSpinBox, self.laplacianWeightDoubleSpinBox)
        DialogCAlphaFlexibleFitting.setTabOrder(self.laplacianWeightDoubleSpinBox, self.hardHandleWeightDoubleSpinBox)
        DialogCAlphaFlexibleFitting.setTabOrder(self.hardHandleWeightDoubleSpinBox, self.softHandleWeightDoubleSpinBox)
        DialogCAlphaFlexibleFitting.setTabOrder(self.softHandleWeightDoubleSpinBox, self.pushButtonRunFlexible)

    def retranslateUi(self, DialogCAlphaFlexibleFitting):
        DialogCAlphaFlexibleFitting.setWindowTitle(_translate("DialogCAlphaFlexibleFitting", "Align backbone to Density", None))
        self.pushButtonLoadHelices.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Load helix annotations into Gorgon", None))
        self.pushButtonLoadHelices.setText(_translate("DialogCAlphaFlexibleFitting", "Load Helices", None))
        self.pushButtonLoadCAlpha.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Load the CAlpha backbone to Gorgon", None))
        self.pushButtonLoadCAlpha.setText(_translate("DialogCAlphaFlexibleFitting", "Load PDB Structure", None))
        self.pushButtonLoadReference.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Load reference into Gorgon", None))
        self.pushButtonLoadReference.setText(_translate("DialogCAlphaFlexibleFitting", "Load Reference", None))
        self.labelCandidateCount.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Maximum dihedral angle between helices that are being aligned", None))
        self.labelCandidateCount.setText(_translate("DialogCAlphaFlexibleFitting", "Max alignments:", None))
        self.spinBoxMaxAlignments.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Maximum difference between centroids of helices being aligned", None))
        self.groupBoxAdvancedSettings.setTitle(_translate("DialogCAlphaFlexibleFitting", "Rigidity Thresholds:", None))
        self.labelJointAngleThreshold_4.setText(_translate("DialogCAlphaFlexibleFitting", "Joint Angle Difference:", None))
        self.spinBoxJointAngleThreshold.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Maximum joint angle difference between helices that are being aligned", None))
        self.spinBoxJointAngleThreshold.setSuffix(_translate("DialogCAlphaFlexibleFitting", "°", None))
        self.labelJointAngleThreshold_3.setText(_translate("DialogCAlphaFlexibleFitting", "Dihedral Angle Difference:", None))
        self.spinBoxDihedralAngleThreshold.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Maximum dihedral angle difference between helices that are being aligned", None))
        self.spinBoxDihedralAngleThreshold.setSuffix(_translate("DialogCAlphaFlexibleFitting", "°", None))
        self.labelJointAngleThreshold_2.setText(_translate("DialogCAlphaFlexibleFitting", "Helix Length Difference:", None))
        self.spinBoxHelixLengthThreshold.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Maximum difference of lengths of helices that are being aligned", None))
        self.spinBoxHelixLengthThreshold.setSuffix(_translate("DialogCAlphaFlexibleFitting", " Å", None))
        self.labelJointAngleThreshold.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Maximum dihedral angle between helices that are being aligned", None))
        self.labelJointAngleThreshold.setText(_translate("DialogCAlphaFlexibleFitting", "Helix Centroid Difference:", None))
        self.spinBoxHelixCentroidThreshold.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Maximum difference between centroids of helices being aligned", None))
        self.spinBoxHelixCentroidThreshold.setSuffix(_translate("DialogCAlphaFlexibleFitting", " Å", None))
        self.pushButtonReset.setText(_translate("DialogCAlphaFlexibleFitting", "Reset", None))
        self.pushButtonOk.setText(_translate("DialogCAlphaFlexibleFitting", "Ok", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRigid), _translate("DialogCAlphaFlexibleFitting", "Rigid Fit", None))
        self.labelAlignment.setText(_translate("DialogCAlphaFlexibleFitting", "Alignment:", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DialogCAlphaFlexibleFitting", "Cluster", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DialogCAlphaFlexibleFitting", "SSE Helix", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DialogCAlphaFlexibleFitting", "PDB Helix", None))
        self.label_2.setText(_translate("DialogCAlphaFlexibleFitting", "Align to Cluster:", None))
        self.groupBoxHelixMatching.setTitle(_translate("DialogCAlphaFlexibleFitting", "Helix Matching:", None))
        self.label.setText(_translate("DialogCAlphaFlexibleFitting", "Select one PDB Ribbon Helix and one SSE Cylinder Helix in order to pair them as a cluster.  ", None))
        self.pushButtonMatchHelices.setText(_translate("DialogCAlphaFlexibleFitting", "Match Helices", None))
        self.groupBoxClusterMerging.setTitle(_translate("DialogCAlphaFlexibleFitting", "Merge Clusters:", None))
        self.label_3.setText(_translate("DialogCAlphaFlexibleFitting", "Cluster 1: ", None))
        self.label_4.setText(_translate("DialogCAlphaFlexibleFitting", "Cluster 2:", None))
        self.pushButtonMergeClusters.setText(_translate("DialogCAlphaFlexibleFitting", "Merge Clusters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAlignments), _translate("DialogCAlphaFlexibleFitting", "Alignments", None))
        self.radioButtonFlexibleFitting.setToolTip(_translate("DialogCAlphaFlexibleFitting", "Align the backbone to the density while allowing for deformations", None))
        self.radioButtonFlexibleFitting.setText(_translate("DialogCAlphaFlexibleFitting", "Flexible Alignment", None))
        self.radioButtonInterpolation.setText(_translate("DialogCAlphaFlexibleFitting", "Interpolation", None))
        self.groupBoxFlexibleSettings.setTitle(_translate("DialogCAlphaFlexibleFitting", "Flexible Fitting Settings:", None))
        self.doRigidInitializationLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Do Rigid Initialization", None))
        self.neighborhoodSizeLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Neighborhood Size", None))
        self.neighborhoodSizeSpinBox.setSuffix(_translate("DialogCAlphaFlexibleFitting", " Neighbors", None))
        self.laplacianWeightLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Laplacian Weight", None))
        self.hardHandleWeightLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Hard Handle Weight", None))
        self.softHandleWeightLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Soft Handle Weight", None))
        self.useSoftHandlesLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Use Soft Handles", None))
        self.pushButtonRunFlexible.setText(_translate("DialogCAlphaFlexibleFitting", "Ok", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFlexibleFit), _translate("DialogCAlphaFlexibleFitting", "Flexible Fit", None))
        self.groupBoxValidationSettings.setTitle(_translate("DialogCAlphaFlexibleFitting", "Validation Settings:", None))
        self.usePerfectMatchingLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Perfect Matching", None))
        self.visualizePairwiseDistanceLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Visualize Pairwise Distance", None))
        self.farthestDistColorLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Farthest distance color:", None))
        self.closestDistColorLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Closest distance color:", None))
        self.useHueColors.setText(_translate("DialogCAlphaFlexibleFitting", "Hue color spectrum", None))
        self.groupBoxResults.setTitle(_translate("DialogCAlphaFlexibleFitting", "Results:", None))
        self.showRMSDLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Root-mean-square deviation", None))
        self.showHausdorffLabel.setText(_translate("DialogCAlphaFlexibleFitting", "Hausdorff distance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabValidation), _translate("DialogCAlphaFlexibleFitting", "Validation", None))

from colored_push_button import ColoredPushButton
