# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_calpha_flexible_fitting.ui'
#
# Created: Thu Jun 17 13:42:08 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogCAlphaFlexibleFitting(object):
    def setupUi(self, DialogCAlphaFlexibleFitting):
        DialogCAlphaFlexibleFitting.setObjectName("DialogCAlphaFlexibleFitting")
        DialogCAlphaFlexibleFitting.resize(282, 343)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogCAlphaFlexibleFitting.sizePolicy().hasHeightForWidth())
        DialogCAlphaFlexibleFitting.setSizePolicy(sizePolicy)
        DialogCAlphaFlexibleFitting.setMinimumSize(QtCore.QSize(270, 296))
        self.verticalLayout_3 = QtGui.QVBoxLayout(DialogCAlphaFlexibleFitting)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonLoadHelices = QtGui.QPushButton(DialogCAlphaFlexibleFitting)
        self.pushButtonLoadHelices.setObjectName("pushButtonLoadHelices")
        self.horizontalLayout.addWidget(self.pushButtonLoadHelices)
        self.pushButtonLoadCAlpha = QtGui.QPushButton(DialogCAlphaFlexibleFitting)
        self.pushButtonLoadCAlpha.setObjectName("pushButtonLoadCAlpha")
        self.horizontalLayout.addWidget(self.pushButtonLoadCAlpha)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(DialogCAlphaFlexibleFitting)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonRigidFitting = QtGui.QRadioButton(self.tabSettings)
        self.radioButtonRigidFitting.setObjectName("radioButtonRigidFitting")
        self.horizontalLayout_2.addWidget(self.radioButtonRigidFitting)
        self.radioButtonFlexibleFitting = QtGui.QRadioButton(self.tabSettings)
        self.radioButtonFlexibleFitting.setChecked(True)
        self.radioButtonFlexibleFitting.setObjectName("radioButtonFlexibleFitting")
        self.horizontalLayout_2.addWidget(self.radioButtonFlexibleFitting)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelCandidateCount = QtGui.QLabel(self.tabSettings)
        self.labelCandidateCount.setObjectName("labelCandidateCount")
        self.horizontalLayout_4.addWidget(self.labelCandidateCount)
        self.spinBoxMaxAlignments = QtGui.QSpinBox(self.tabSettings)
        self.spinBoxMaxAlignments.setMinimum(1)
        self.spinBoxMaxAlignments.setMaximum(100)
        self.spinBoxMaxAlignments.setProperty("value", QtCore.QVariant(5))
        self.spinBoxMaxAlignments.setObjectName("spinBoxMaxAlignments")
        self.horizontalLayout_4.addWidget(self.spinBoxMaxAlignments)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBoxAdvancedSettings = QtGui.QGroupBox(self.tabSettings)
        self.groupBoxAdvancedSettings.setObjectName("groupBoxAdvancedSettings")
        self.formLayout = QtGui.QFormLayout(self.groupBoxAdvancedSettings)
        self.formLayout.setObjectName("formLayout")
        self.labelJointAngleThreshold = QtGui.QLabel(self.groupBoxAdvancedSettings)
        self.labelJointAngleThreshold.setObjectName("labelJointAngleThreshold")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelJointAngleThreshold)
        self.spinBoxJointAngleThreshold = QtGui.QSpinBox(self.groupBoxAdvancedSettings)
        self.spinBoxJointAngleThreshold.setMaximum(180)
        self.spinBoxJointAngleThreshold.setProperty("value", QtCore.QVariant(30))
        self.spinBoxJointAngleThreshold.setObjectName("spinBoxJointAngleThreshold")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxJointAngleThreshold)
        self.labelJointAngleThreshold_2 = QtGui.QLabel(self.groupBoxAdvancedSettings)
        self.labelJointAngleThreshold_2.setObjectName("labelJointAngleThreshold_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelJointAngleThreshold_2)
        self.spinBoxDihedralAngleThreshold = QtGui.QSpinBox(self.groupBoxAdvancedSettings)
        self.spinBoxDihedralAngleThreshold.setMaximum(180)
        self.spinBoxDihedralAngleThreshold.setProperty("value", QtCore.QVariant(30))
        self.spinBoxDihedralAngleThreshold.setObjectName("spinBoxDihedralAngleThreshold")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxDihedralAngleThreshold)
        self.labelJointAngleThreshold_3 = QtGui.QLabel(self.groupBoxAdvancedSettings)
        self.labelJointAngleThreshold_3.setObjectName("labelJointAngleThreshold_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelJointAngleThreshold_3)
        self.spinBoxHelixLengthThreshold = QtGui.QSpinBox(self.groupBoxAdvancedSettings)
        self.spinBoxHelixLengthThreshold.setMaximum(50)
        self.spinBoxHelixLengthThreshold.setProperty("value", QtCore.QVariant(10))
        self.spinBoxHelixLengthThreshold.setObjectName("spinBoxHelixLengthThreshold")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxHelixLengthThreshold)
        self.labelJointAngleThreshold_4 = QtGui.QLabel(self.groupBoxAdvancedSettings)
        self.labelJointAngleThreshold_4.setObjectName("labelJointAngleThreshold_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelJointAngleThreshold_4)
        self.spinBoxHelixCentroidThreshold = QtGui.QSpinBox(self.groupBoxAdvancedSettings)
        self.spinBoxHelixCentroidThreshold.setMaximum(50)
        self.spinBoxHelixCentroidThreshold.setProperty("value", QtCore.QVariant(5))
        self.spinBoxHelixCentroidThreshold.setObjectName("spinBoxHelixCentroidThreshold")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxHelixCentroidThreshold)
        self.verticalLayout.addWidget(self.groupBoxAdvancedSettings)
        self.tabWidget.addTab(self.tabSettings, "")
        self.tabAlignments = QtGui.QWidget()
        self.tabAlignments.setObjectName("tabAlignments")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabAlignments)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelAlignment = QtGui.QLabel(self.tabAlignments)
        self.labelAlignment.setObjectName("labelAlignment")
        self.horizontalLayout_5.addWidget(self.labelAlignment)
        self.comboBoxAlignment = QtGui.QComboBox(self.tabAlignments)
        self.comboBoxAlignment.setObjectName("comboBoxAlignment")
        self.horizontalLayout_5.addWidget(self.comboBoxAlignment)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtGui.QTableWidget(self.tabAlignments)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tabAlignments, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(358, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(DialogCAlphaFlexibleFitting)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(DialogCAlphaFlexibleFitting)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DialogCAlphaFlexibleFitting.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DialogCAlphaFlexibleFitting.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogCAlphaFlexibleFitting)
        DialogCAlphaFlexibleFitting.setTabOrder(self.pushButtonLoadHelices, self.pushButtonLoadCAlpha)
        DialogCAlphaFlexibleFitting.setTabOrder(self.pushButtonLoadCAlpha, self.tabWidget)
        DialogCAlphaFlexibleFitting.setTabOrder(self.tabWidget, self.radioButtonRigidFitting)
        DialogCAlphaFlexibleFitting.setTabOrder(self.radioButtonRigidFitting, self.radioButtonFlexibleFitting)
        DialogCAlphaFlexibleFitting.setTabOrder(self.radioButtonFlexibleFitting, self.spinBoxMaxAlignments)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxMaxAlignments, self.spinBoxJointAngleThreshold)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxJointAngleThreshold, self.spinBoxDihedralAngleThreshold)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxDihedralAngleThreshold, self.spinBoxHelixLengthThreshold)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxHelixLengthThreshold, self.spinBoxHelixCentroidThreshold)
        DialogCAlphaFlexibleFitting.setTabOrder(self.spinBoxHelixCentroidThreshold, self.buttonBox)
        DialogCAlphaFlexibleFitting.setTabOrder(self.buttonBox, self.comboBoxAlignment)
        DialogCAlphaFlexibleFitting.setTabOrder(self.comboBoxAlignment, self.tableWidget)

    def retranslateUi(self, DialogCAlphaFlexibleFitting):
        DialogCAlphaFlexibleFitting.setWindowTitle(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Align backbone to Density", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoadHelices.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Load helix annotations into Gorgon", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoadHelices.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Load Helices", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoadCAlpha.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Load the CAlpha backbone to Gorgon", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoadCAlpha.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Load PDB Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRigidFitting.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Align the backbone to the density without allowing for deformations", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRigidFitting.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Rigid Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonFlexibleFitting.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Align the backbone to the density while allowing for deformations", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonFlexibleFitting.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Flexible Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCandidateCount.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Maximum dihedral angle between helices that are being aligned", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCandidateCount.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Max alignments:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxMaxAlignments.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Maximum difference between centroids of helices being aligned", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxAdvancedSettings.setTitle(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Rigidity Thresholds:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelJointAngleThreshold.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Joint Angle Difference:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxJointAngleThreshold.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Maximum joint angle difference between helices that are being aligned", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxJointAngleThreshold.setSuffix(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.labelJointAngleThreshold_2.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Dihedral Angle Difference:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxDihedralAngleThreshold.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Maximum dihedral angle difference between helices that are being aligned", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxDihedralAngleThreshold.setSuffix(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.labelJointAngleThreshold_3.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Helix Length Difference:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxHelixLengthThreshold.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Maximum difference of lengths of helices that are being aligned", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxHelixLengthThreshold.setSuffix(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", " Å", None, QtGui.QApplication.UnicodeUTF8))
        self.labelJointAngleThreshold_4.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Maximum dihedral angle between helices that are being aligned", None, QtGui.QApplication.UnicodeUTF8))
        self.labelJointAngleThreshold_4.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Helix Centroid Difference:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxHelixCentroidThreshold.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Maximum difference between centroids of helices being aligned", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxHelixCentroidThreshold.setSuffix(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", " Å", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAlignment.setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Alignment:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "SSE Helix", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "PDB Helix", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAlignments), QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Alignments", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox.setToolTip(QtGui.QApplication.translate("DialogCAlphaFlexibleFitting", "Perform Fitting", None, QtGui.QApplication.UnicodeUTF8))

