# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_model_visualization.ui'
#
# Created: Mon Dec 28 16:05:55 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogModelVisualization(object):
    def setupUi(self, DialogModelVisualization):
        DialogModelVisualization.setObjectName("DialogModelVisualization")
        DialogModelVisualization.resize(253, 301)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogModelVisualization.sizePolicy().hasHeightForWidth())
        DialogModelVisualization.setSizePolicy(sizePolicy)
        self.gridlayout = QtGui.QGridLayout(DialogModelVisualization)
        self.gridlayout.setObjectName("gridlayout")
        self.tabWidget = QtGui.QTabWidget(DialogModelVisualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxDisplayStyle = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxDisplayStyle.sizePolicy().hasHeightForWidth())
        self.groupBoxDisplayStyle.setSizePolicy(sizePolicy)
        self.groupBoxDisplayStyle.setObjectName("groupBoxDisplayStyle")
        self.gridlayout1 = QtGui.QGridLayout(self.groupBoxDisplayStyle)
        self.gridlayout1.setObjectName("gridlayout1")
        self.radioButtonWireframe = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonWireframe.setObjectName("radioButtonWireframe")
        self.gridlayout1.addWidget(self.radioButtonWireframe, 0, 0, 1, 1)
        self.radioButtonFlat = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonFlat.setObjectName("radioButtonFlat")
        self.gridlayout1.addWidget(self.radioButtonFlat, 0, 1, 1, 1)
        self.radioButtonSmooth = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonSmooth.setChecked(True)
        self.radioButtonSmooth.setObjectName("radioButtonSmooth")
        self.gridlayout1.addWidget(self.radioButtonSmooth, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBoxDisplayStyle, 0, 0, 1, 3)
        self.checkBoxBoundingBox = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBoundingBox.sizePolicy().hasHeightForWidth())
        self.checkBoxBoundingBox.setSizePolicy(sizePolicy)
        self.checkBoxBoundingBox.setChecked(True)
        self.checkBoxBoundingBox.setObjectName("checkBoxBoundingBox")
        self.gridLayout.addWidget(self.checkBoxBoundingBox, 1, 0, 1, 2)
        self.pushButtonBoundingBoxColor = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBoundingBoxColor.sizePolicy().hasHeightForWidth())
        self.pushButtonBoundingBoxColor.setSizePolicy(sizePolicy)
        self.pushButtonBoundingBoxColor.setObjectName("pushButtonBoundingBoxColor")
        self.gridLayout.addWidget(self.pushButtonBoundingBoxColor, 1, 2, 1, 1)
        self.checkBoxModelVisible = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxModelVisible.sizePolicy().hasHeightForWidth())
        self.checkBoxModelVisible.setSizePolicy(sizePolicy)
        self.checkBoxModelVisible.setChecked(True)
        self.checkBoxModelVisible.setObjectName("checkBoxModelVisible")
        self.gridLayout.addWidget(self.checkBoxModelVisible, 2, 0, 1, 2)
        self.pushButtonModelColor = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonModelColor.sizePolicy().hasHeightForWidth())
        self.pushButtonModelColor.setSizePolicy(sizePolicy)
        self.pushButtonModelColor.setObjectName("pushButtonModelColor")
        self.gridLayout.addWidget(self.pushButtonModelColor, 2, 2, 1, 1)
        self.checkBoxModel2Visible = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxModel2Visible.sizePolicy().hasHeightForWidth())
        self.checkBoxModel2Visible.setSizePolicy(sizePolicy)
        self.checkBoxModel2Visible.setChecked(True)
        self.checkBoxModel2Visible.setObjectName("checkBoxModel2Visible")
        self.gridLayout.addWidget(self.checkBoxModel2Visible, 3, 0, 1, 2)
        self.pushButtonModel2Color = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonModel2Color.sizePolicy().hasHeightForWidth())
        self.pushButtonModel2Color.setSizePolicy(sizePolicy)
        self.pushButtonModel2Color.setObjectName("pushButtonModel2Color")
        self.gridLayout.addWidget(self.pushButtonModel2Color, 3, 2, 1, 1)
        self.checkBoxModel3Visible = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxModel3Visible.sizePolicy().hasHeightForWidth())
        self.checkBoxModel3Visible.setSizePolicy(sizePolicy)
        self.checkBoxModel3Visible.setChecked(True)
        self.checkBoxModel3Visible.setObjectName("checkBoxModel3Visible")
        self.gridLayout.addWidget(self.checkBoxModel3Visible, 4, 0, 1, 2)
        self.pushButtonModel3Color = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonModel3Color.sizePolicy().hasHeightForWidth())
        self.pushButtonModel3Color.setSizePolicy(sizePolicy)
        self.pushButtonModel3Color.setObjectName("pushButtonModel3Color")
        self.gridLayout.addWidget(self.pushButtonModel3Color, 4, 2, 1, 1)
        self.labelThickness = QtGui.QLabel(self.tab)
        self.labelThickness.setObjectName("labelThickness")
        self.gridLayout.addWidget(self.labelThickness, 5, 0, 1, 1)
        self.spinBoxThickness = QtGui.QSpinBox(self.tab)
        self.spinBoxThickness.setProperty("value", QtCore.QVariant(3))
        self.spinBoxThickness.setObjectName("spinBoxThickness")
        self.gridLayout.addWidget(self.spinBoxThickness, 5, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridlayout2 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout2.setObjectName("gridlayout2")
        self.GroupBoxLocation_2 = QtGui.QGroupBox(self.tab_2)
        self.GroupBoxLocation_2.setObjectName("GroupBoxLocation_2")
        self.gridlayout3 = QtGui.QGridLayout(self.GroupBoxLocation_2)
        self.gridlayout3.setMargin(6)
        self.gridlayout3.setSpacing(0)
        self.gridlayout3.setObjectName("gridlayout3")
        self.labelSizeX = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeX.sizePolicy().hasHeightForWidth())
        self.labelSizeX.setSizePolicy(sizePolicy)
        self.labelSizeX.setObjectName("labelSizeX")
        self.gridlayout3.addWidget(self.labelSizeX, 0, 0, 1, 1)
        self.doubleSpinBoxSizeX = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeX.setDecimals(8)
        self.doubleSpinBoxSizeX.setMaximum(1e+014)
        self.doubleSpinBoxSizeX.setProperty("value", QtCore.QVariant(1.0))
        self.doubleSpinBoxSizeX.setObjectName("doubleSpinBoxSizeX")
        self.gridlayout3.addWidget(self.doubleSpinBoxSizeX, 0, 1, 1, 1)
        self.labelSizeY = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeY.sizePolicy().hasHeightForWidth())
        self.labelSizeY.setSizePolicy(sizePolicy)
        self.labelSizeY.setObjectName("labelSizeY")
        self.gridlayout3.addWidget(self.labelSizeY, 1, 0, 1, 1)
        self.doubleSpinBoxSizeY = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeY.setDecimals(8)
        self.doubleSpinBoxSizeY.setMaximum(1e+014)
        self.doubleSpinBoxSizeY.setProperty("value", QtCore.QVariant(1.0))
        self.doubleSpinBoxSizeY.setObjectName("doubleSpinBoxSizeY")
        self.gridlayout3.addWidget(self.doubleSpinBoxSizeY, 1, 1, 1, 1)
        self.labelSizeZ = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeZ.sizePolicy().hasHeightForWidth())
        self.labelSizeZ.setSizePolicy(sizePolicy)
        self.labelSizeZ.setObjectName("labelSizeZ")
        self.gridlayout3.addWidget(self.labelSizeZ, 2, 0, 1, 1)
        self.doubleSpinBoxSizeZ = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeZ.setDecimals(8)
        self.doubleSpinBoxSizeZ.setMaximum(1e+014)
        self.doubleSpinBoxSizeZ.setProperty("value", QtCore.QVariant(1.0))
        self.doubleSpinBoxSizeZ.setObjectName("doubleSpinBoxSizeZ")
        self.gridlayout3.addWidget(self.doubleSpinBoxSizeZ, 2, 1, 1, 1)
        self.gridlayout2.addWidget(self.GroupBoxLocation_2, 0, 0, 1, 1)
        self.GroupBoxLocation = QtGui.QGroupBox(self.tab_2)
        self.GroupBoxLocation.setObjectName("GroupBoxLocation")
        self.gridlayout4 = QtGui.QGridLayout(self.GroupBoxLocation)
        self.gridlayout4.setMargin(6)
        self.gridlayout4.setSpacing(0)
        self.gridlayout4.setObjectName("gridlayout4")
        self.labelLocationX = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationX.sizePolicy().hasHeightForWidth())
        self.labelLocationX.setSizePolicy(sizePolicy)
        self.labelLocationX.setObjectName("labelLocationX")
        self.gridlayout4.addWidget(self.labelLocationX, 0, 0, 1, 1)
        self.doubleSpinBoxLocationX = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationX.setDecimals(8)
        self.doubleSpinBoxLocationX.setMinimum(-1e+014)
        self.doubleSpinBoxLocationX.setMaximum(1e+014)
        self.doubleSpinBoxLocationX.setProperty("value", QtCore.QVariant(0.0))
        self.doubleSpinBoxLocationX.setObjectName("doubleSpinBoxLocationX")
        self.gridlayout4.addWidget(self.doubleSpinBoxLocationX, 0, 1, 1, 1)
        self.labelLocationY = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationY.sizePolicy().hasHeightForWidth())
        self.labelLocationY.setSizePolicy(sizePolicy)
        self.labelLocationY.setObjectName("labelLocationY")
        self.gridlayout4.addWidget(self.labelLocationY, 1, 0, 1, 1)
        self.doubleSpinBoxLocationY = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationY.setDecimals(8)
        self.doubleSpinBoxLocationY.setMinimum(-1e+014)
        self.doubleSpinBoxLocationY.setMaximum(1e+014)
        self.doubleSpinBoxLocationY.setObjectName("doubleSpinBoxLocationY")
        self.gridlayout4.addWidget(self.doubleSpinBoxLocationY, 1, 1, 1, 1)
        self.labelLocationZ = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationZ.sizePolicy().hasHeightForWidth())
        self.labelLocationZ.setSizePolicy(sizePolicy)
        self.labelLocationZ.setObjectName("labelLocationZ")
        self.gridlayout4.addWidget(self.labelLocationZ, 2, 0, 1, 1)
        self.doubleSpinBoxLocationZ = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationZ.setDecimals(8)
        self.doubleSpinBoxLocationZ.setMinimum(-1e+014)
        self.doubleSpinBoxLocationZ.setMaximum(1e+014)
        self.doubleSpinBoxLocationZ.setObjectName("doubleSpinBoxLocationZ")
        self.gridlayout4.addWidget(self.doubleSpinBoxLocationZ, 2, 1, 1, 1)
        self.gridlayout2.addWidget(self.GroupBoxLocation, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridlayout5 = QtGui.QGridLayout(self.tab_3)
        self.gridlayout5.setObjectName("gridlayout5")
        self.label_2 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridlayout5.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelModelName = QtGui.QLabel(self.tab_3)
        self.labelModelName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelModelName.setWordWrap(True)
        self.labelModelName.setObjectName("labelModelName")
        self.gridlayout5.addWidget(self.labelModelName, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridlayout5.addWidget(self.label, 1, 0, 1, 1)
        self.labelModelSize = QtGui.QLabel(self.tab_3)
        self.labelModelSize.setObjectName("labelModelSize")
        self.gridlayout5.addWidget(self.labelModelSize, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout5.addItem(spacerItem1, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridlayout6 = QtGui.QGridLayout()
        self.gridlayout6.setObjectName("gridlayout6")
        self.pushButtonCenter = QtGui.QPushButton(DialogModelVisualization)
        self.pushButtonCenter.setObjectName("pushButtonCenter")
        self.gridlayout6.addWidget(self.pushButtonCenter, 0, 0, 1, 1)
        self.pushButtonClose = QtGui.QPushButton(DialogModelVisualization)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridlayout6.addWidget(self.pushButtonClose, 0, 1, 1, 1)
        self.gridlayout.addLayout(self.gridlayout6, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem2, 2, 0, 1, 1)

        self.retranslateUi(DialogModelVisualization)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogModelVisualization)
        DialogModelVisualization.setTabOrder(self.pushButtonCenter, self.pushButtonClose)
        DialogModelVisualization.setTabOrder(self.pushButtonClose, self.tabWidget)
        DialogModelVisualization.setTabOrder(self.tabWidget, self.radioButtonWireframe)
        DialogModelVisualization.setTabOrder(self.radioButtonWireframe, self.radioButtonFlat)
        DialogModelVisualization.setTabOrder(self.radioButtonFlat, self.radioButtonSmooth)
        DialogModelVisualization.setTabOrder(self.radioButtonSmooth, self.checkBoxBoundingBox)
        DialogModelVisualization.setTabOrder(self.checkBoxBoundingBox, self.pushButtonBoundingBoxColor)
        DialogModelVisualization.setTabOrder(self.pushButtonBoundingBoxColor, self.checkBoxModelVisible)
        DialogModelVisualization.setTabOrder(self.checkBoxModelVisible, self.pushButtonModelColor)
        DialogModelVisualization.setTabOrder(self.pushButtonModelColor, self.checkBoxModel2Visible)
        DialogModelVisualization.setTabOrder(self.checkBoxModel2Visible, self.pushButtonModel2Color)
        DialogModelVisualization.setTabOrder(self.pushButtonModel2Color, self.spinBoxThickness)
        DialogModelVisualization.setTabOrder(self.spinBoxThickness, self.doubleSpinBoxSizeX)
        DialogModelVisualization.setTabOrder(self.doubleSpinBoxSizeX, self.doubleSpinBoxSizeY)
        DialogModelVisualization.setTabOrder(self.doubleSpinBoxSizeY, self.doubleSpinBoxSizeZ)
        DialogModelVisualization.setTabOrder(self.doubleSpinBoxSizeZ, self.doubleSpinBoxLocationX)
        DialogModelVisualization.setTabOrder(self.doubleSpinBoxLocationX, self.doubleSpinBoxLocationY)
        DialogModelVisualization.setTabOrder(self.doubleSpinBoxLocationY, self.doubleSpinBoxLocationZ)

    def retranslateUi(self, DialogModelVisualization):
        DialogModelVisualization.setWindowTitle(QtGui.QApplication.translate("DialogModelVisualization", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDisplayStyle.setTitle(QtGui.QApplication.translate("DialogModelVisualization", "Display Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonWireframe.setText(QtGui.QApplication.translate("DialogModelVisualization", "Wireframe", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonFlat.setText(QtGui.QApplication.translate("DialogModelVisualization", "Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSmooth.setText(QtGui.QApplication.translate("DialogModelVisualization", "Smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxBoundingBox.setText(QtGui.QApplication.translate("DialogModelVisualization", "Show outline box colored:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxModelVisible.setText(QtGui.QApplication.translate("DialogModelVisualization", "Show model colored:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxModel2Visible.setText(QtGui.QApplication.translate("DialogModelVisualization", "Show 2nd model colored:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxModel3Visible.setText(QtGui.QApplication.translate("DialogModelVisualization", "Show 3rd model colored:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelThickness.setText(QtGui.QApplication.translate("DialogModelVisualization", "Thickness:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogModelVisualization", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.GroupBoxLocation_2.setTitle(QtGui.QApplication.translate("DialogModelVisualization", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeX.setText(QtGui.QApplication.translate("DialogModelVisualization", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeY.setText(QtGui.QApplication.translate("DialogModelVisualization", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeZ.setText(QtGui.QApplication.translate("DialogModelVisualization", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.GroupBoxLocation.setTitle(QtGui.QApplication.translate("DialogModelVisualization", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLocationX.setText(QtGui.QApplication.translate("DialogModelVisualization", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLocationY.setText(QtGui.QApplication.translate("DialogModelVisualization", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLocationZ.setText(QtGui.QApplication.translate("DialogModelVisualization", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogModelVisualization", "Positioning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogModelVisualization", "File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelModelName.setText(QtGui.QApplication.translate("DialogModelVisualization", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogModelVisualization", "Model Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelModelSize.setText(QtGui.QApplication.translate("DialogModelVisualization", "{X, Y, Z}", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("DialogModelVisualization", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCenter.setText(QtGui.QApplication.translate("DialogModelVisualization", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClose.setText(QtGui.QApplication.translate("DialogModelVisualization", "Unload Model", None, QtGui.QApplication.UnicodeUTF8))

from colored_push_button import ColoredPushButton
