# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_reference_atom_visualization.ui'
#
# Created: Wed Oct 29 09:23:40 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogReferenceAtomVisualization(object):
    def setupUi(self, DialogReferenceAtomVisualization):
        DialogReferenceAtomVisualization.setObjectName(_fromUtf8("DialogReferenceAtomVisualization"))
        DialogReferenceAtomVisualization.resize(342, 632)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogReferenceAtomVisualization.sizePolicy().hasHeightForWidth())
        DialogReferenceAtomVisualization.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(DialogReferenceAtomVisualization)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(DialogReferenceAtomVisualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBoxDisplayStyle = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxDisplayStyle.sizePolicy().hasHeightForWidth())
        self.groupBoxDisplayStyle.setSizePolicy(sizePolicy)
        self.groupBoxDisplayStyle.setObjectName(_fromUtf8("groupBoxDisplayStyle"))
        self.gridlayout = QtGui.QGridLayout(self.groupBoxDisplayStyle)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.radioButtonBackbone = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonBackbone.setChecked(True)
        self.radioButtonBackbone.setObjectName(_fromUtf8("radioButtonBackbone"))
        self.gridlayout.addWidget(self.radioButtonBackbone, 0, 0, 1, 1)
        self.radioButtonRibbon = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonRibbon.setObjectName(_fromUtf8("radioButtonRibbon"))
        self.gridlayout.addWidget(self.radioButtonRibbon, 0, 1, 1, 1)
        self.radioButtonSideChain = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonSideChain.setChecked(False)
        self.radioButtonSideChain.setObjectName(_fromUtf8("radioButtonSideChain"))
        self.gridlayout.addWidget(self.radioButtonSideChain, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxDisplayStyle)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBoxBoundingBox = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBoundingBox.sizePolicy().hasHeightForWidth())
        self.checkBoxBoundingBox.setSizePolicy(sizePolicy)
        self.checkBoxBoundingBox.setChecked(True)
        self.checkBoxBoundingBox.setObjectName(_fromUtf8("checkBoxBoundingBox"))
        self.gridLayout_2.addWidget(self.checkBoxBoundingBox, 0, 0, 1, 1)
        self.pushButtonBoundingBoxColor = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBoundingBoxColor.sizePolicy().hasHeightForWidth())
        self.pushButtonBoundingBoxColor.setSizePolicy(sizePolicy)
        self.pushButtonBoundingBoxColor.setText(_fromUtf8(""))
        self.pushButtonBoundingBoxColor.setObjectName(_fromUtf8("pushButtonBoundingBoxColor"))
        self.gridLayout_2.addWidget(self.pushButtonBoundingBoxColor, 0, 1, 1, 1)
        self.labelColor1 = QtGui.QLabel(self.tab)
        self.labelColor1.setObjectName(_fromUtf8("labelColor1"))
        self.gridLayout_2.addWidget(self.labelColor1, 1, 0, 1, 1)
        self.pushButtonColor1 = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColor1.sizePolicy().hasHeightForWidth())
        self.pushButtonColor1.setSizePolicy(sizePolicy)
        self.pushButtonColor1.setText(_fromUtf8(""))
        self.pushButtonColor1.setObjectName(_fromUtf8("pushButtonColor1"))
        self.gridLayout_2.addWidget(self.pushButtonColor1, 1, 1, 1, 1)
        self.labelColor2 = QtGui.QLabel(self.tab)
        self.labelColor2.setObjectName(_fromUtf8("labelColor2"))
        self.gridLayout_2.addWidget(self.labelColor2, 2, 0, 1, 1)
        self.pushButtonColor2 = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColor2.sizePolicy().hasHeightForWidth())
        self.pushButtonColor2.setSizePolicy(sizePolicy)
        self.pushButtonColor2.setText(_fromUtf8(""))
        self.pushButtonColor2.setObjectName(_fromUtf8("pushButtonColor2"))
        self.gridLayout_2.addWidget(self.pushButtonColor2, 2, 1, 1, 1)
        self.labelColor3 = QtGui.QLabel(self.tab)
        self.labelColor3.setObjectName(_fromUtf8("labelColor3"))
        self.gridLayout_2.addWidget(self.labelColor3, 3, 0, 1, 1)
        self.pushButtonColor3 = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColor3.sizePolicy().hasHeightForWidth())
        self.pushButtonColor3.setSizePolicy(sizePolicy)
        self.pushButtonColor3.setText(_fromUtf8(""))
        self.pushButtonColor3.setObjectName(_fromUtf8("pushButtonColor3"))
        self.gridLayout_2.addWidget(self.pushButtonColor3, 3, 1, 1, 1)
        self.labelColor4 = QtGui.QLabel(self.tab)
        self.labelColor4.setObjectName(_fromUtf8("labelColor4"))
        self.gridLayout_2.addWidget(self.labelColor4, 4, 0, 1, 1)
        self.pushButtonColor4 = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColor4.sizePolicy().hasHeightForWidth())
        self.pushButtonColor4.setSizePolicy(sizePolicy)
        self.pushButtonColor4.setText(_fromUtf8(""))
        self.pushButtonColor4.setObjectName(_fromUtf8("pushButtonColor4"))
        self.gridLayout_2.addWidget(self.pushButtonColor4, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.labelSmoothness = QtGui.QLabel(self.tab)
        self.labelSmoothness.setObjectName(_fromUtf8("labelSmoothness"))
        self.verticalLayout.addWidget(self.labelSmoothness)
        self.hSliderSmoothness = QtGui.QSlider(self.tab)
        self.hSliderSmoothness.setMinimum(2)
        self.hSliderSmoothness.setMaximum(20)
        self.hSliderSmoothness.setProperty("value", 10)
        self.hSliderSmoothness.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderSmoothness.setTickPosition(QtGui.QSlider.TicksBelow)
        self.hSliderSmoothness.setTickInterval(5)
        self.hSliderSmoothness.setObjectName(_fromUtf8("hSliderSmoothness"))
        self.verticalLayout.addWidget(self.hSliderSmoothness)
        self.labelRoundedness = QtGui.QLabel(self.tab)
        self.labelRoundedness.setObjectName(_fromUtf8("labelRoundedness"))
        self.verticalLayout.addWidget(self.labelRoundedness)
        self.hSliderRoundedness = QtGui.QSlider(self.tab)
        self.hSliderRoundedness.setMinimum(3)
        self.hSliderRoundedness.setMaximum(20)
        self.hSliderRoundedness.setProperty("value", 10)
        self.hSliderRoundedness.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderRoundedness.setTickPosition(QtGui.QSlider.TicksBelow)
        self.hSliderRoundedness.setTickInterval(3)
        self.hSliderRoundedness.setObjectName(_fromUtf8("hSliderRoundedness"))
        self.verticalLayout.addWidget(self.hSliderRoundedness)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.rslider = QtGui.QSlider(self.tab)
        self.rslider.setMaximum(100)
        self.rslider.setPageStep(10)
        self.rslider.setProperty("value", 50)
        self.rslider.setOrientation(QtCore.Qt.Horizontal)
        self.rslider.setObjectName(_fromUtf8("rslider"))
        self.verticalLayout.addWidget(self.rslider)
        self.gslider = QtGui.QSlider(self.tab)
        self.gslider.setMaximum(100)
        self.gslider.setProperty("value", 50)
        self.gslider.setOrientation(QtCore.Qt.Horizontal)
        self.gslider.setObjectName(_fromUtf8("gslider"))
        self.verticalLayout.addWidget(self.gslider)
        self.bslider = QtGui.QSlider(self.tab)
        self.bslider.setMaximum(100)
        self.bslider.setProperty("value", 50)
        self.bslider.setOrientation(QtCore.Qt.Horizontal)
        self.bslider.setObjectName(_fromUtf8("bslider"))
        self.verticalLayout.addWidget(self.bslider)
        self.aslider = QtGui.QSlider(self.tab)
        self.aslider.setMaximum(100)
        self.aslider.setProperty("value", 50)
        self.aslider.setSliderPosition(50)
        self.aslider.setOrientation(QtCore.Qt.Horizontal)
        self.aslider.setObjectName(_fromUtf8("aslider"))
        self.verticalLayout.addWidget(self.aslider)
        self.groupBoxShow = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxShow.sizePolicy().hasHeightForWidth())
        self.groupBoxShow.setSizePolicy(sizePolicy)
        self.groupBoxShow.setObjectName(_fromUtf8("groupBoxShow"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxShow)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxShowAtoms = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowAtoms.setChecked(True)
        self.checkBoxShowAtoms.setObjectName(_fromUtf8("checkBoxShowAtoms"))
        self.gridLayout.addWidget(self.checkBoxShowAtoms, 0, 0, 1, 1)
        self.checkBoxShowBonds = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowBonds.setChecked(True)
        self.checkBoxShowBonds.setObjectName(_fromUtf8("checkBoxShowBonds"))
        self.gridLayout.addWidget(self.checkBoxShowBonds, 0, 1, 1, 1)
        self.checkBoxShowHelices = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowHelices.setChecked(True)
        self.checkBoxShowHelices.setObjectName(_fromUtf8("checkBoxShowHelices"))
        self.gridLayout.addWidget(self.checkBoxShowHelices, 1, 0, 1, 1)
        self.checkBoxShowStrands = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowStrands.setChecked(True)
        self.checkBoxShowStrands.setObjectName(_fromUtf8("checkBoxShowStrands"))
        self.gridLayout.addWidget(self.checkBoxShowStrands, 1, 1, 1, 1)
        self.checkBoxShowLoops = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowLoops.setChecked(True)
        self.checkBoxShowLoops.setObjectName(_fromUtf8("checkBoxShowLoops"))
        self.gridLayout.addWidget(self.checkBoxShowLoops, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxShow)
        spacerItem = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridlayout1 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.GroupBoxLocation_2 = QtGui.QGroupBox(self.tab_2)
        self.GroupBoxLocation_2.setObjectName(_fromUtf8("GroupBoxLocation_2"))
        self.gridlayout2 = QtGui.QGridLayout(self.GroupBoxLocation_2)
        self.gridlayout2.setMargin(6)
        self.gridlayout2.setSpacing(0)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.labelSizeX = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeX.sizePolicy().hasHeightForWidth())
        self.labelSizeX.setSizePolicy(sizePolicy)
        self.labelSizeX.setObjectName(_fromUtf8("labelSizeX"))
        self.gridlayout2.addWidget(self.labelSizeX, 0, 0, 1, 1)
        self.doubleSpinBoxSizeX = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeX.setDecimals(8)
        self.doubleSpinBoxSizeX.setMaximum(1e+14)
        self.doubleSpinBoxSizeX.setProperty("value", 1.0)
        self.doubleSpinBoxSizeX.setObjectName(_fromUtf8("doubleSpinBoxSizeX"))
        self.gridlayout2.addWidget(self.doubleSpinBoxSizeX, 0, 1, 1, 1)
        self.labelSizeY = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeY.sizePolicy().hasHeightForWidth())
        self.labelSizeY.setSizePolicy(sizePolicy)
        self.labelSizeY.setObjectName(_fromUtf8("labelSizeY"))
        self.gridlayout2.addWidget(self.labelSizeY, 1, 0, 1, 1)
        self.doubleSpinBoxSizeY = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeY.setDecimals(8)
        self.doubleSpinBoxSizeY.setMaximum(1e+14)
        self.doubleSpinBoxSizeY.setProperty("value", 1.0)
        self.doubleSpinBoxSizeY.setObjectName(_fromUtf8("doubleSpinBoxSizeY"))
        self.gridlayout2.addWidget(self.doubleSpinBoxSizeY, 1, 1, 1, 1)
        self.labelSizeZ = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeZ.sizePolicy().hasHeightForWidth())
        self.labelSizeZ.setSizePolicy(sizePolicy)
        self.labelSizeZ.setObjectName(_fromUtf8("labelSizeZ"))
        self.gridlayout2.addWidget(self.labelSizeZ, 2, 0, 1, 1)
        self.doubleSpinBoxSizeZ = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeZ.setDecimals(8)
        self.doubleSpinBoxSizeZ.setMaximum(1e+14)
        self.doubleSpinBoxSizeZ.setProperty("value", 1.0)
        self.doubleSpinBoxSizeZ.setObjectName(_fromUtf8("doubleSpinBoxSizeZ"))
        self.gridlayout2.addWidget(self.doubleSpinBoxSizeZ, 2, 1, 1, 1)
        self.gridlayout1.addWidget(self.GroupBoxLocation_2, 0, 0, 1, 1)
        self.GroupBoxLocation = QtGui.QGroupBox(self.tab_2)
        self.GroupBoxLocation.setObjectName(_fromUtf8("GroupBoxLocation"))
        self.gridlayout3 = QtGui.QGridLayout(self.GroupBoxLocation)
        self.gridlayout3.setMargin(6)
        self.gridlayout3.setSpacing(0)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.labelLocationX = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationX.sizePolicy().hasHeightForWidth())
        self.labelLocationX.setSizePolicy(sizePolicy)
        self.labelLocationX.setObjectName(_fromUtf8("labelLocationX"))
        self.gridlayout3.addWidget(self.labelLocationX, 0, 0, 1, 1)
        self.doubleSpinBoxLocationX = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationX.setDecimals(8)
        self.doubleSpinBoxLocationX.setMinimum(-1e+14)
        self.doubleSpinBoxLocationX.setMaximum(1e+14)
        self.doubleSpinBoxLocationX.setProperty("value", 0.0)
        self.doubleSpinBoxLocationX.setObjectName(_fromUtf8("doubleSpinBoxLocationX"))
        self.gridlayout3.addWidget(self.doubleSpinBoxLocationX, 0, 1, 1, 1)
        self.labelLocationY = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationY.sizePolicy().hasHeightForWidth())
        self.labelLocationY.setSizePolicy(sizePolicy)
        self.labelLocationY.setObjectName(_fromUtf8("labelLocationY"))
        self.gridlayout3.addWidget(self.labelLocationY, 1, 0, 1, 1)
        self.doubleSpinBoxLocationY = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationY.setDecimals(8)
        self.doubleSpinBoxLocationY.setMinimum(-1e+14)
        self.doubleSpinBoxLocationY.setMaximum(1e+14)
        self.doubleSpinBoxLocationY.setObjectName(_fromUtf8("doubleSpinBoxLocationY"))
        self.gridlayout3.addWidget(self.doubleSpinBoxLocationY, 1, 1, 1, 1)
        self.labelLocationZ = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationZ.sizePolicy().hasHeightForWidth())
        self.labelLocationZ.setSizePolicy(sizePolicy)
        self.labelLocationZ.setObjectName(_fromUtf8("labelLocationZ"))
        self.gridlayout3.addWidget(self.labelLocationZ, 2, 0, 1, 1)
        self.doubleSpinBoxLocationZ = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationZ.setDecimals(8)
        self.doubleSpinBoxLocationZ.setMinimum(-1e+14)
        self.doubleSpinBoxLocationZ.setMaximum(1e+14)
        self.doubleSpinBoxLocationZ.setObjectName(_fromUtf8("doubleSpinBoxLocationZ"))
        self.gridlayout3.addWidget(self.doubleSpinBoxLocationZ, 2, 1, 1, 1)
        self.gridlayout1.addWidget(self.GroupBoxLocation, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridlayout4 = QtGui.QGridLayout(self.tab_3)
        self.gridlayout4.setObjectName(_fromUtf8("gridlayout4"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout4.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelModelName = QtGui.QLabel(self.tab_3)
        self.labelModelName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelModelName.setWordWrap(True)
        self.labelModelName.setObjectName(_fromUtf8("labelModelName"))
        self.gridlayout4.addWidget(self.labelModelName, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout4.addWidget(self.label, 1, 0, 1, 1)
        self.labelModelSize = QtGui.QLabel(self.tab_3)
        self.labelModelSize.setObjectName(_fromUtf8("labelModelSize"))
        self.gridlayout4.addWidget(self.labelModelSize, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem1, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridlayout5 = QtGui.QGridLayout()
        self.gridlayout5.setObjectName(_fromUtf8("gridlayout5"))
        self.pushButtonCenter = QtGui.QPushButton(DialogReferenceAtomVisualization)
        self.pushButtonCenter.setObjectName(_fromUtf8("pushButtonCenter"))
        self.gridlayout5.addWidget(self.pushButtonCenter, 0, 0, 1, 1)
        self.pushButtonClose = QtGui.QPushButton(DialogReferenceAtomVisualization)
        self.pushButtonClose.setObjectName(_fromUtf8("pushButtonClose"))
        self.gridlayout5.addWidget(self.pushButtonClose, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridlayout5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        self.retranslateUi(DialogReferenceAtomVisualization)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogReferenceAtomVisualization)
        DialogReferenceAtomVisualization.setTabOrder(self.tabWidget, self.radioButtonBackbone)
        DialogReferenceAtomVisualization.setTabOrder(self.radioButtonBackbone, self.radioButtonRibbon)
        DialogReferenceAtomVisualization.setTabOrder(self.radioButtonRibbon, self.radioButtonSideChain)
        DialogReferenceAtomVisualization.setTabOrder(self.radioButtonSideChain, self.checkBoxBoundingBox)
        DialogReferenceAtomVisualization.setTabOrder(self.checkBoxBoundingBox, self.pushButtonBoundingBoxColor)
        DialogReferenceAtomVisualization.setTabOrder(self.pushButtonBoundingBoxColor, self.pushButtonColor1)
        DialogReferenceAtomVisualization.setTabOrder(self.pushButtonColor1, self.pushButtonColor2)
        DialogReferenceAtomVisualization.setTabOrder(self.pushButtonColor2, self.pushButtonColor3)
        DialogReferenceAtomVisualization.setTabOrder(self.pushButtonColor3, self.pushButtonColor4)
        DialogReferenceAtomVisualization.setTabOrder(self.pushButtonColor4, self.checkBoxShowAtoms)
        DialogReferenceAtomVisualization.setTabOrder(self.checkBoxShowAtoms, self.checkBoxShowBonds)
        DialogReferenceAtomVisualization.setTabOrder(self.checkBoxShowBonds, self.checkBoxShowHelices)
        DialogReferenceAtomVisualization.setTabOrder(self.checkBoxShowHelices, self.checkBoxShowStrands)
        DialogReferenceAtomVisualization.setTabOrder(self.checkBoxShowStrands, self.checkBoxShowLoops)
        DialogReferenceAtomVisualization.setTabOrder(self.checkBoxShowLoops, self.pushButtonCenter)
        DialogReferenceAtomVisualization.setTabOrder(self.pushButtonCenter, self.pushButtonClose)
        DialogReferenceAtomVisualization.setTabOrder(self.pushButtonClose, self.doubleSpinBoxSizeX)
        DialogReferenceAtomVisualization.setTabOrder(self.doubleSpinBoxSizeX, self.doubleSpinBoxSizeY)
        DialogReferenceAtomVisualization.setTabOrder(self.doubleSpinBoxSizeY, self.doubleSpinBoxSizeZ)
        DialogReferenceAtomVisualization.setTabOrder(self.doubleSpinBoxSizeZ, self.doubleSpinBoxLocationX)
        DialogReferenceAtomVisualization.setTabOrder(self.doubleSpinBoxLocationX, self.doubleSpinBoxLocationY)
        DialogReferenceAtomVisualization.setTabOrder(self.doubleSpinBoxLocationY, self.doubleSpinBoxLocationZ)

    def retranslateUi(self, DialogReferenceAtomVisualization):
        DialogReferenceAtomVisualization.setWindowTitle(_translate("DialogReferenceAtomVisualization", "Visualization", None))
        self.groupBoxDisplayStyle.setTitle(_translate("DialogReferenceAtomVisualization", "Reference Display Style:", None))
        self.radioButtonBackbone.setText(_translate("DialogReferenceAtomVisualization", "Backbone", None))
        self.radioButtonRibbon.setText(_translate("DialogReferenceAtomVisualization", "Ribbon", None))
        self.radioButtonSideChain.setText(_translate("DialogReferenceAtomVisualization", "Side Chains", None))
        self.checkBoxBoundingBox.setText(_translate("DialogReferenceAtomVisualization", "Show outline box colored:", None))
        self.labelColor1.setText(_translate("DialogReferenceAtomVisualization", "Color 1:", None))
        self.labelColor2.setText(_translate("DialogReferenceAtomVisualization", "Color 2:", None))
        self.labelColor3.setText(_translate("DialogReferenceAtomVisualization", "Color 3:", None))
        self.labelColor4.setText(_translate("DialogReferenceAtomVisualization", "Color 4:", None))
        self.labelSmoothness.setText(_translate("DialogReferenceAtomVisualization", "Smoothness", None))
        self.labelRoundedness.setText(_translate("DialogReferenceAtomVisualization", "Roundedness", None))
        self.label_3.setText(_translate("DialogReferenceAtomVisualization", "r, g, b, a", None))
        self.groupBoxShow.setTitle(_translate("DialogReferenceAtomVisualization", "Show:", None))
        self.checkBoxShowAtoms.setText(_translate("DialogReferenceAtomVisualization", "Atoms", None))
        self.checkBoxShowBonds.setText(_translate("DialogReferenceAtomVisualization", "Bonds", None))
        self.checkBoxShowHelices.setText(_translate("DialogReferenceAtomVisualization", "α-helices", None))
        self.checkBoxShowStrands.setText(_translate("DialogReferenceAtomVisualization", "β-strands", None))
        self.checkBoxShowLoops.setText(_translate("DialogReferenceAtomVisualization", "Loops", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogReferenceAtomVisualization", "Visualization", None))
        self.GroupBoxLocation_2.setTitle(_translate("DialogReferenceAtomVisualization", "Scale:", None))
        self.labelSizeX.setText(_translate("DialogReferenceAtomVisualization", "X:", None))
        self.labelSizeY.setText(_translate("DialogReferenceAtomVisualization", "Y:", None))
        self.labelSizeZ.setText(_translate("DialogReferenceAtomVisualization", "Z:", None))
        self.GroupBoxLocation.setTitle(_translate("DialogReferenceAtomVisualization", "Location:", None))
        self.labelLocationX.setText(_translate("DialogReferenceAtomVisualization", "X:", None))
        self.labelLocationY.setText(_translate("DialogReferenceAtomVisualization", "Y:", None))
        self.labelLocationZ.setText(_translate("DialogReferenceAtomVisualization", "Z:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogReferenceAtomVisualization", "Positioning", None))
        self.label_2.setText(_translate("DialogReferenceAtomVisualization", "File Name:", None))
        self.labelModelName.setText(_translate("DialogReferenceAtomVisualization", "...", None))
        self.label.setText(_translate("DialogReferenceAtomVisualization", "Model Size:", None))
        self.labelModelSize.setText(_translate("DialogReferenceAtomVisualization", "{X, Y, Z}", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogReferenceAtomVisualization", "Properties", None))
        self.pushButtonCenter.setText(_translate("DialogReferenceAtomVisualization", "Center", "Center the model"))
        self.pushButtonClose.setText(_translate("DialogReferenceAtomVisualization", "Unload Reference", "Close the model"))

from colored_push_button import ColoredPushButton
