# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_sse_helix_correspondence_finder.ui'
#
# Created: Wed Dec 23 15:35:42 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogSSEHelixCorrespondenceFinder(object):
    def setupUi(self, DialogSSEHelixCorrespondenceFinder):
        DialogSSEHelixCorrespondenceFinder.setObjectName("DialogSSEHelixCorrespondenceFinder")
        DialogSSEHelixCorrespondenceFinder.resize(382, 616)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogSSEHelixCorrespondenceFinder.sizePolicy().hasHeightForWidth())
        DialogSSEHelixCorrespondenceFinder.setSizePolicy(sizePolicy)
        DialogSSEHelixCorrespondenceFinder.setMinimumSize(QtCore.QSize(0, 567))
        DialogSSEHelixCorrespondenceFinder.setMaximumSize(QtCore.QSize(999999, 999999))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(DialogSSEHelixCorrespondenceFinder)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_7 = QtGui.QSplitter(DialogSSEHelixCorrespondenceFinder)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter_7.sizePolicy().hasHeightForWidth())
        self.splitter_7.setSizePolicy(sizePolicy)
        self.splitter_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_7.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setOpaqueResize(True)
        self.splitter_7.setObjectName("splitter_7")
        self.tabWidget = QtGui.QTabWidget(self.splitter_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDataSources = QtGui.QWidget()
        self.tabDataSources.setObjectName("tabDataSources")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabDataSources)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtGui.QGroupBox(self.tabDataSources)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEditSkeletonFile = QtGui.QLineEdit(self.groupBox_7)
        self.lineEditSkeletonFile.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSkeletonFile.sizePolicy().hasHeightForWidth())
        self.lineEditSkeletonFile.setSizePolicy(sizePolicy)
        self.lineEditSkeletonFile.setObjectName("lineEditSkeletonFile")
        self.gridLayout.addWidget(self.lineEditSkeletonFile, 0, 1, 1, 1)
        self.pushButtonGetSkeletonFile = QtGui.QPushButton(self.groupBox_7)
        self.pushButtonGetSkeletonFile.setObjectName("pushButtonGetSkeletonFile")
        self.gridLayout.addWidget(self.pushButtonGetSkeletonFile, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setLineWidth(0)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditSequenceFile = QtGui.QLineEdit(self.groupBox_7)
        self.lineEditSequenceFile.setEnabled(False)
        self.lineEditSequenceFile.setObjectName("lineEditSequenceFile")
        self.gridLayout.addWidget(self.lineEditSequenceFile, 1, 1, 1, 1)
        self.pushButtonGetSequenceFile = QtGui.QPushButton(self.groupBox_7)
        self.pushButtonGetSequenceFile.setObjectName("pushButtonGetSequenceFile")
        self.gridLayout.addWidget(self.pushButtonGetSequenceFile, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_7)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lineEditHelixLengthFile = QtGui.QLineEdit(self.groupBox_7)
        self.lineEditHelixLengthFile.setEnabled(False)
        self.lineEditHelixLengthFile.setObjectName("lineEditHelixLengthFile")
        self.gridLayout.addWidget(self.lineEditHelixLengthFile, 2, 1, 1, 1)
        self.pushButtonGetHelixLengthFile = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonGetHelixLengthFile.sizePolicy().hasHeightForWidth())
        self.pushButtonGetHelixLengthFile.setSizePolicy(sizePolicy)
        self.pushButtonGetHelixLengthFile.setObjectName("pushButtonGetHelixLengthFile")
        self.gridLayout.addWidget(self.pushButtonGetHelixLengthFile, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEditHelixLocationFile = QtGui.QLineEdit(self.groupBox_7)
        self.lineEditHelixLocationFile.setEnabled(False)
        self.lineEditHelixLocationFile.setObjectName("lineEditHelixLocationFile")
        self.gridLayout.addWidget(self.lineEditHelixLocationFile, 3, 1, 1, 1)
        self.pushButtonGetHelixLocationFile = QtGui.QPushButton(self.groupBox_7)
        self.pushButtonGetHelixLocationFile.setObjectName("pushButtonGetHelixLocationFile")
        self.gridLayout.addWidget(self.pushButtonGetHelixLocationFile, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEditSheetLocationFile = QtGui.QLineEdit(self.groupBox_7)
        self.lineEditSheetLocationFile.setEnabled(False)
        self.lineEditSheetLocationFile.setObjectName("lineEditSheetLocationFile")
        self.gridLayout.addWidget(self.lineEditSheetLocationFile, 4, 1, 1, 1)
        self.pushButtonGetSheetLocationFile = QtGui.QPushButton(self.groupBox_7)
        self.pushButtonGetSheetLocationFile.setObjectName("pushButtonGetSheetLocationFile")
        self.gridLayout.addWidget(self.pushButtonGetSheetLocationFile, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.tabDataSources)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_20 = QtGui.QLabel(self.groupBox_8)
        self.label_20.setMinimumSize(QtCore.QSize(98, 0))
        self.label_20.setLineWidth(0)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 0, 1, 1)
        self.lineEditSettingsFile = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditSettingsFile.setEnabled(False)
        self.lineEditSettingsFile.setObjectName("lineEditSettingsFile")
        self.gridLayout_6.addWidget(self.lineEditSettingsFile, 0, 1, 1, 1)
        self.pushButtonGetSettingsFile = QtGui.QPushButton(self.groupBox_8)
        self.pushButtonGetSettingsFile.setObjectName("pushButtonGetSettingsFile")
        self.gridLayout_6.addWidget(self.pushButtonGetSettingsFile, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_8)
        spacerItem = QtGui.QSpacerItem(338, 198, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tabDataSources, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(151, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBoxShowSkeleton = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowSkeleton.sizePolicy().hasHeightForWidth())
        self.checkBoxShowSkeleton.setSizePolicy(sizePolicy)
        self.checkBoxShowSkeleton.setTristate(False)
        self.checkBoxShowSkeleton.setObjectName("checkBoxShowSkeleton")
        self.gridLayout_5.addWidget(self.checkBoxShowSkeleton, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 0, 1, 1)
        self.checkBoxShowHelices = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowHelices.sizePolicy().hasHeightForWidth())
        self.checkBoxShowHelices.setSizePolicy(sizePolicy)
        self.checkBoxShowHelices.setTristate(False)
        self.checkBoxShowHelices.setObjectName("checkBoxShowHelices")
        self.gridLayout_5.addWidget(self.checkBoxShowHelices, 2, 0, 1, 1)
        self.checkBoxShowHelixCorners = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowHelixCorners.sizePolicy().hasHeightForWidth())
        self.checkBoxShowHelixCorners.setSizePolicy(sizePolicy)
        self.checkBoxShowHelixCorners.setTristate(False)
        self.checkBoxShowHelixCorners.setObjectName("checkBoxShowHelixCorners")
        self.gridLayout_5.addWidget(self.checkBoxShowHelixCorners, 3, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 4, 0, 1, 1)
        self.checkBoxShowSheets = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowSheets.sizePolicy().hasHeightForWidth())
        self.checkBoxShowSheets.setSizePolicy(sizePolicy)
        self.checkBoxShowSheets.setTristate(False)
        self.checkBoxShowSheets.setObjectName("checkBoxShowSheets")
        self.gridLayout_5.addWidget(self.checkBoxShowSheets, 5, 0, 1, 1)
        self.checkBoxShowSheetColors = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowSheetColors.sizePolicy().hasHeightForWidth())
        self.checkBoxShowSheetColors.setSizePolicy(sizePolicy)
        self.checkBoxShowSheetColors.setTristate(False)
        self.checkBoxShowSheetColors.setObjectName("checkBoxShowSheetColors")
        self.gridLayout_5.addWidget(self.checkBoxShowSheetColors, 6, 0, 1, 1)
        self.checkBoxShowSheetCorners = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowSheetCorners.sizePolicy().hasHeightForWidth())
        self.checkBoxShowSheetCorners.setSizePolicy(sizePolicy)
        self.checkBoxShowSheetCorners.setTristate(False)
        self.checkBoxShowSheetCorners.setObjectName("checkBoxShowSheetCorners")
        self.gridLayout_5.addWidget(self.checkBoxShowSheetCorners, 7, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.groupBox_4)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 8, 0, 1, 1)
        self.checkBoxShowAllPaths = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowAllPaths.sizePolicy().hasHeightForWidth())
        self.checkBoxShowAllPaths.setSizePolicy(sizePolicy)
        self.checkBoxShowAllPaths.setMinimumSize(QtCore.QSize(119, 0))
        self.checkBoxShowAllPaths.setTristate(False)
        self.checkBoxShowAllPaths.setObjectName("checkBoxShowAllPaths")
        self.gridLayout_5.addWidget(self.checkBoxShowAllPaths, 9, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 291, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tabGraphSettings = QtGui.QWidget()
        self.tabGraphSettings.setObjectName("tabGraphSettings")
        self.gridLayout_21 = QtGui.QGridLayout(self.tabGraphSettings)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.groupBox_6 = QtGui.QGroupBox(self.tabGraphSettings)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.gridLayout_12.addWidget(self.label_13, 0, 0, 1, 1)
        self.doubleSpinBoxEuclideanToPDBRatio = QtGui.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxEuclideanToPDBRatio.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxEuclideanToPDBRatio.setSizePolicy(sizePolicy)
        self.doubleSpinBoxEuclideanToPDBRatio.setDecimals(4)
        self.doubleSpinBoxEuclideanToPDBRatio.setMaximum(10000000.0)
        self.doubleSpinBoxEuclideanToPDBRatio.setProperty("value", QtCore.QVariant(10.0))
        self.doubleSpinBoxEuclideanToPDBRatio.setObjectName("doubleSpinBoxEuclideanToPDBRatio")
        self.gridLayout_12.addWidget(self.doubleSpinBoxEuclideanToPDBRatio, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_12)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.radioButtonAbsoluteDifference = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonAbsoluteDifference.sizePolicy().hasHeightForWidth())
        self.radioButtonAbsoluteDifference.setSizePolicy(sizePolicy)
        self.radioButtonAbsoluteDifference.setChecked(True)
        self.radioButtonAbsoluteDifference.setObjectName("radioButtonAbsoluteDifference")
        self.horizontalLayout_3.addWidget(self.radioButtonAbsoluteDifference)
        self.radioButtonNormalizedDifference = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonNormalizedDifference.sizePolicy().hasHeightForWidth())
        self.radioButtonNormalizedDifference.setSizePolicy(sizePolicy)
        self.radioButtonNormalizedDifference.setObjectName("radioButtonNormalizedDifference")
        self.horizontalLayout_3.addWidget(self.radioButtonNormalizedDifference)
        self.radioButtonQuadraticError = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonQuadraticError.sizePolicy().hasHeightForWidth())
        self.radioButtonQuadraticError.setSizePolicy(sizePolicy)
        self.radioButtonQuadraticError.setObjectName("radioButtonQuadraticError")
        self.horizontalLayout_3.addWidget(self.radioButtonQuadraticError)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_13.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabGraphSettings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 1)
        self.doubleSpinBoxLoopImportance = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxLoopImportance.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxLoopImportance.setSizePolicy(sizePolicy)
        self.doubleSpinBoxLoopImportance.setDecimals(4)
        self.doubleSpinBoxLoopImportance.setMaximum(100.0)
        self.doubleSpinBoxLoopImportance.setSingleStep(0.1)
        self.doubleSpinBoxLoopImportance.setProperty("value", QtCore.QVariant(0.2))
        self.doubleSpinBoxLoopImportance.setObjectName("doubleSpinBoxLoopImportance")
        self.gridLayout_8.addWidget(self.doubleSpinBoxLoopImportance, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.doubleSpinBoxEuclideanLoopUsedPenalty = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxEuclideanLoopUsedPenalty.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxEuclideanLoopUsedPenalty.setSizePolicy(sizePolicy)
        self.doubleSpinBoxEuclideanLoopUsedPenalty.setDecimals(4)
        self.doubleSpinBoxEuclideanLoopUsedPenalty.setMaximum(1000000000.0)
        self.doubleSpinBoxEuclideanLoopUsedPenalty.setProperty("value", QtCore.QVariant(5.0))
        self.doubleSpinBoxEuclideanLoopUsedPenalty.setObjectName("doubleSpinBoxEuclideanLoopUsedPenalty")
        self.gridLayout_8.addWidget(self.doubleSpinBoxEuclideanLoopUsedPenalty, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tabGraphSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_28 = QtGui.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.gridLayout_20.addWidget(self.label_28, 0, 0, 1, 1)
        self.doubleSpinBoxHelixImportance = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxHelixImportance.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxHelixImportance.setSizePolicy(sizePolicy)
        self.doubleSpinBoxHelixImportance.setDecimals(4)
        self.doubleSpinBoxHelixImportance.setMaximum(100.0)
        self.doubleSpinBoxHelixImportance.setSingleStep(0.1)
        self.doubleSpinBoxHelixImportance.setProperty("value", QtCore.QVariant(1.0))
        self.doubleSpinBoxHelixImportance.setObjectName("doubleSpinBoxHelixImportance")
        self.gridLayout_20.addWidget(self.doubleSpinBoxHelixImportance, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox)
        self.label_29.setObjectName("label_29")
        self.gridLayout_20.addWidget(self.label_29, 1, 0, 1, 1)
        self.doubleSpinBoxHelixMissingPenalty = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxHelixMissingPenalty.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxHelixMissingPenalty.setSizePolicy(sizePolicy)
        self.doubleSpinBoxHelixMissingPenalty.setProperty("text", QtCore.QVariant(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "5.0000", None, QtGui.QApplication.UnicodeUTF8)))
        self.doubleSpinBoxHelixMissingPenalty.setDecimals(4)
        self.doubleSpinBoxHelixMissingPenalty.setMaximum(1000000000.0)
        self.doubleSpinBoxHelixMissingPenalty.setProperty("value", QtCore.QVariant(5.0))
        self.doubleSpinBoxHelixMissingPenalty.setObjectName("doubleSpinBoxHelixMissingPenalty")
        self.gridLayout_20.addWidget(self.doubleSpinBoxHelixMissingPenalty, 1, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout_20.addWidget(self.label_30, 2, 0, 1, 1)
        self.doubleSpinBoxHelixMissingPenaltyScaled = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxHelixMissingPenaltyScaled.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxHelixMissingPenaltyScaled.setSizePolicy(sizePolicy)
        self.doubleSpinBoxHelixMissingPenaltyScaled.setProperty("text", QtCore.QVariant(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "0.0000", None, QtGui.QApplication.UnicodeUTF8)))
        self.doubleSpinBoxHelixMissingPenaltyScaled.setDecimals(4)
        self.doubleSpinBoxHelixMissingPenaltyScaled.setMaximum(10.0)
        self.doubleSpinBoxHelixMissingPenaltyScaled.setSingleStep(0.01)
        self.doubleSpinBoxHelixMissingPenaltyScaled.setProperty("value", QtCore.QVariant(0.0))
        self.doubleSpinBoxHelixMissingPenaltyScaled.setObjectName("doubleSpinBoxHelixMissingPenaltyScaled")
        self.gridLayout_20.addWidget(self.doubleSpinBoxHelixMissingPenaltyScaled, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox)
        self.label_31.setObjectName("label_31")
        self.gridLayout_20.addWidget(self.label_31, 3, 0, 1, 1)
        self.doubleSpinBoxEndHelixMissingPenalty = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxEndHelixMissingPenalty.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxEndHelixMissingPenalty.setSizePolicy(sizePolicy)
        self.doubleSpinBoxEndHelixMissingPenalty.setDecimals(4)
        self.doubleSpinBoxEndHelixMissingPenalty.setMaximum(1000000000.0)
        self.doubleSpinBoxEndHelixMissingPenalty.setSingleStep(1.0)
        self.doubleSpinBoxEndHelixMissingPenalty.setProperty("value", QtCore.QVariant(8.0))
        self.doubleSpinBoxEndHelixMissingPenalty.setObjectName("doubleSpinBoxEndHelixMissingPenalty")
        self.gridLayout_20.addWidget(self.doubleSpinBoxEndHelixMissingPenalty, 3, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tabGraphSettings)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 1, 0, 1, 1)
        self.doubleSpinBoxSheetImportance = QtGui.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxSheetImportance.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxSheetImportance.setSizePolicy(sizePolicy)
        self.doubleSpinBoxSheetImportance.setProperty("text", QtCore.QVariant(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "1.0000", None, QtGui.QApplication.UnicodeUTF8)))
        self.doubleSpinBoxSheetImportance.setDecimals(4)
        self.doubleSpinBoxSheetImportance.setMaximum(100.0)
        self.doubleSpinBoxSheetImportance.setSingleStep(0.1)
        self.doubleSpinBoxSheetImportance.setProperty("value", QtCore.QVariant(1.0))
        self.doubleSpinBoxSheetImportance.setObjectName("doubleSpinBoxSheetImportance")
        self.gridLayout_10.addWidget(self.doubleSpinBoxSheetImportance, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 2, 0, 1, 1)
        self.doubleSpinBoxSheetMissingPenalty = QtGui.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxSheetMissingPenalty.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxSheetMissingPenalty.setSizePolicy(sizePolicy)
        self.doubleSpinBoxSheetMissingPenalty.setDecimals(4)
        self.doubleSpinBoxSheetMissingPenalty.setMaximum(1000000000.0)
        self.doubleSpinBoxSheetMissingPenalty.setProperty("value", QtCore.QVariant(5.0))
        self.doubleSpinBoxSheetMissingPenalty.setObjectName("doubleSpinBoxSheetMissingPenalty")
        self.gridLayout_10.addWidget(self.doubleSpinBoxSheetMissingPenalty, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 3, 0, 1, 1)
        self.doubleSpinBoxSheetMissingPenaltyScaled = QtGui.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxSheetMissingPenaltyScaled.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxSheetMissingPenaltyScaled.setSizePolicy(sizePolicy)
        self.doubleSpinBoxSheetMissingPenaltyScaled.setDecimals(4)
        self.doubleSpinBoxSheetMissingPenaltyScaled.setMaximum(10.0)
        self.doubleSpinBoxSheetMissingPenaltyScaled.setSingleStep(0.01)
        self.doubleSpinBoxSheetMissingPenaltyScaled.setProperty("value", QtCore.QVariant(0.0))
        self.doubleSpinBoxSheetMissingPenaltyScaled.setObjectName("doubleSpinBoxSheetMissingPenaltyScaled")
        self.gridLayout_10.addWidget(self.doubleSpinBoxSheetMissingPenaltyScaled, 3, 1, 1, 1)
        self.checkBoxIncludeSheets = QtGui.QCheckBox(self.groupBox_5)
        self.checkBoxIncludeSheets.setObjectName("checkBoxIncludeSheets")
        self.gridLayout_10.addWidget(self.checkBoxIncludeSheets, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_5, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem2, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tabGraphSettings, "")
        self.tabAdvancedSettings = QtGui.QWidget()
        self.tabAdvancedSettings.setObjectName("tabAdvancedSettings")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabAdvancedSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_9 = QtGui.QGroupBox(self.tabAdvancedSettings)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout = QtGui.QFormLayout(self.groupBox_9)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtGui.QLabel(self.groupBox_9)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.spinBoxBorderMarginThreshold = QtGui.QSpinBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxBorderMarginThreshold.sizePolicy().hasHeightForWidth())
        self.spinBoxBorderMarginThreshold.setSizePolicy(sizePolicy)
        self.spinBoxBorderMarginThreshold.setProperty("value", QtCore.QVariant(3))
        self.spinBoxBorderMarginThreshold.setObjectName("spinBoxBorderMarginThreshold")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxBorderMarginThreshold)
        self.label_6 = QtGui.QLabel(self.groupBox_9)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.doubleSpinBoxEuclideanDistance = QtGui.QDoubleSpinBox(self.groupBox_9)
        self.doubleSpinBoxEuclideanDistance.setDecimals(4)
        self.doubleSpinBoxEuclideanDistance.setMaximum(1000000000.0)
        self.doubleSpinBoxEuclideanDistance.setProperty("value", QtCore.QVariant(0.0))
        self.doubleSpinBoxEuclideanDistance.setObjectName("doubleSpinBoxEuclideanDistance")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxEuclideanDistance)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.tabAdvancedSettings)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBoxMissingHelices = QtGui.QCheckBox(self.groupBox_10)
        self.checkBoxMissingHelices.setObjectName("checkBoxMissingHelices")
        self.gridLayout_7.addWidget(self.checkBoxMissingHelices, 0, 0, 1, 1)
        self.spinBoxMissingHelixCount = QtGui.QSpinBox(self.groupBox_10)
        self.spinBoxMissingHelixCount.setEnabled(False)
        self.spinBoxMissingHelixCount.setObjectName("spinBoxMissingHelixCount")
        self.gridLayout_7.addWidget(self.spinBoxMissingHelixCount, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.groupBox_3 = QtGui.QGroupBox(self.tabAdvancedSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(151, 161))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBoxMinSheetSize = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxMinSheetSize.sizePolicy().hasHeightForWidth())
        self.spinBoxMinSheetSize.setSizePolicy(sizePolicy)
        self.spinBoxMinSheetSize.setMinimumSize(QtCore.QSize(51, 0))
        self.spinBoxMinSheetSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBoxMinSheetSize.setMaximum(99999)
        self.spinBoxMinSheetSize.setProperty("value", QtCore.QVariant(10))
        self.spinBoxMinSheetSize.setObjectName("spinBoxMinSheetSize")
        self.gridLayout_3.addWidget(self.spinBoxMinSheetSize, 0, 1, 1, 1)
        self.splitter_5 = QtGui.QSplitter(self.groupBox_3)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_16 = QtGui.QLabel(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(120, 0))
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.splitter_5, 1, 0, 1, 1)
        self.doubleSpinBoxMaxSheetDistance = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxMaxSheetDistance.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxMaxSheetDistance.setSizePolicy(sizePolicy)
        self.doubleSpinBoxMaxSheetDistance.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBoxMaxSheetDistance.setProperty("text", QtCore.QVariant(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "5.0000", None, QtGui.QApplication.UnicodeUTF8)))
        self.doubleSpinBoxMaxSheetDistance.setDecimals(4)
        self.doubleSpinBoxMaxSheetDistance.setMaximum(1000000000.0)
        self.doubleSpinBoxMaxSheetDistance.setProperty("value", QtCore.QVariant(5.0))
        self.doubleSpinBoxMaxSheetDistance.setObjectName("doubleSpinBoxMaxSheetDistance")
        self.gridLayout_3.addWidget(self.doubleSpinBoxMaxSheetDistance, 1, 1, 1, 1)
        self.splitter_8 = QtGui.QSplitter(self.groupBox_3)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_21 = QtGui.QLabel(self.splitter_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(120, 0))
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.splitter_8, 2, 0, 1, 1)
        self.doubleSpinBoxSheetSelfLoopLength = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxSheetSelfLoopLength.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxSheetSelfLoopLength.setSizePolicy(sizePolicy)
        self.doubleSpinBoxSheetSelfLoopLength.setProperty("text", QtCore.QVariant(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "5.0000", None, QtGui.QApplication.UnicodeUTF8)))
        self.doubleSpinBoxSheetSelfLoopLength.setDecimals(4)
        self.doubleSpinBoxSheetSelfLoopLength.setMaximum(1000000000.0)
        self.doubleSpinBoxSheetSelfLoopLength.setProperty("value", QtCore.QVariant(5.0))
        self.doubleSpinBoxSheetSelfLoopLength.setObjectName("doubleSpinBoxSheetSelfLoopLength")
        self.gridLayout_3.addWidget(self.doubleSpinBoxSheetSelfLoopLength, 2, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.groupBox_3)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 6, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(187, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButtonRebuildGraph = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonRebuildGraph.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRebuildGraph.sizePolicy().hasHeightForWidth())
        self.pushButtonRebuildGraph.setSizePolicy(sizePolicy)
        self.pushButtonRebuildGraph.setMinimumSize(QtCore.QSize(150, 23))
        self.pushButtonRebuildGraph.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonRebuildGraph.setObjectName("pushButtonRebuildGraph")
        self.horizontalLayout.addWidget(self.pushButtonRebuildGraph)
        self.gridLayout_3.addLayout(self.horizontalLayout, 7, 0, 1, 2)
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.doubleSpinBoxSheetMergeThreshold = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBoxSheetMergeThreshold.setDecimals(4)
        self.doubleSpinBoxSheetMergeThreshold.setMaximum(10000.0)
        self.doubleSpinBoxSheetMergeThreshold.setProperty("value", QtCore.QVariant(3.0))
        self.doubleSpinBoxSheetMergeThreshold.setObjectName("doubleSpinBoxSheetMergeThreshold")
        self.gridLayout_3.addWidget(self.doubleSpinBoxSheetMergeThreshold, 3, 1, 1, 1)
        self.splitter_3 = QtGui.QSplitter(self.groupBox_3)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_15 = QtGui.QLabel(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(120, 0))
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.checkBoxIncludeStrands = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxIncludeStrands.setObjectName("checkBoxIncludeStrands")
        self.gridLayout_3.addWidget(self.checkBoxIncludeStrands, 5, 0, 1, 2)
        self.checkBoxMissingSheets = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxMissingSheets.setObjectName("checkBoxMissingSheets")
        self.gridLayout_3.addWidget(self.checkBoxMissingSheets, 4, 0, 1, 1)
        self.spinBoxMissingSheetCount = QtGui.QSpinBox(self.groupBox_3)
        self.spinBoxMissingSheetCount.setEnabled(False)
        self.spinBoxMissingSheetCount.setObjectName("spinBoxMissingSheetCount")
        self.gridLayout_3.addWidget(self.spinBoxMissingSheetCount, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem4 = QtGui.QSpacerItem(340, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.tabWidget.addTab(self.tabAdvancedSettings, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_15 = QtGui.QGridLayout(self.tab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.labelCorrespondences = QtGui.QLabel(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCorrespondences.sizePolicy().hasHeightForWidth())
        self.labelCorrespondences.setSizePolicy(sizePolicy)
        self.labelCorrespondences.setMinimumSize(QtCore.QSize(100, 0))
        self.labelCorrespondences.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelCorrespondences.setObjectName("labelCorrespondences")
        self.comboBoxCorrespondences = QtGui.QComboBox(self.splitter)
        self.comboBoxCorrespondences.setObjectName("comboBoxCorrespondences")
        self.verticalLayout_7.addWidget(self.splitter)
        self.tableWidgetCorrespondenceList = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetCorrespondenceList.sizePolicy().hasHeightForWidth())
        self.tableWidgetCorrespondenceList.setSizePolicy(sizePolicy)
        self.tableWidgetCorrespondenceList.setCornerButtonEnabled(False)
        self.tableWidgetCorrespondenceList.setObjectName("tableWidgetCorrespondenceList")
        self.tableWidgetCorrespondenceList.setColumnCount(3)
        self.tableWidgetCorrespondenceList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCorrespondenceList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCorrespondenceList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCorrespondenceList.setHorizontalHeaderItem(2, item)
        self.verticalLayout_7.addWidget(self.tableWidgetCorrespondenceList)
        self.pushButtonExportToRosetta = QtGui.QPushButton(self.tab)
        self.pushButtonExportToRosetta.setObjectName("pushButtonExportToRosetta")
        self.verticalLayout_7.addWidget(self.pushButtonExportToRosetta)
        self.gridLayout_15.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.splitter_6 = QtGui.QSplitter(self.splitter_7)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.layoutWidget = QtGui.QWidget(self.splitter_6)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridlayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridlayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName("gridlayout")
        self.pushButtonOk = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonOk.setEnabled(False)
        self.pushButtonOk.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.gridlayout.addWidget(self.pushButtonOk, 0, 2, 1, 1)
        self.pushButtonCancel = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridlayout.addWidget(self.pushButtonCancel, 0, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem5, 0, 1, 1, 1)
        self.pushButtonReset = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonReset.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.gridlayout.addWidget(self.pushButtonReset, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.splitter_7)

        self.retranslateUi(DialogSSEHelixCorrespondenceFinder)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogSSEHelixCorrespondenceFinder)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.tabWidget, self.lineEditHelixLengthFile)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.lineEditHelixLengthFile, self.pushButtonGetHelixLengthFile)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.pushButtonGetHelixLengthFile, self.lineEditHelixLocationFile)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.lineEditHelixLocationFile, self.pushButtonGetHelixLocationFile)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.pushButtonGetHelixLocationFile, self.comboBoxCorrespondences)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.comboBoxCorrespondences, self.tableWidgetCorrespondenceList)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.tableWidgetCorrespondenceList, self.pushButtonExportToRosetta)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.pushButtonExportToRosetta, self.pushButtonReset)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.pushButtonReset, self.pushButtonOk)
        DialogSSEHelixCorrespondenceFinder.setTabOrder(self.pushButtonOk, self.pushButtonCancel)

    def retranslateUi(self, DialogSSEHelixCorrespondenceFinder):
        DialogSSEHelixCorrespondenceFinder.setWindowTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Helix and Sheet Correspondence Finder", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Data Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Cryo-EM Skeleton:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGetSkeletonFile.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Sequence:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGetSequenceFile.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Helix Lengths:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGetHelixLengthFile.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "3D Helix Locations:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGetHelixLocationFile.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "3D Sheet Locations:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGetSheetLocationFile.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Data Files, Graph Settings, and Matching Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Settings File:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGetSettingsFile.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataSources), QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Data Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowSkeleton.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Show Skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowHelices.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Show Helices", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowHelixCorners.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Show Helix Corners", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowSheets.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Show SSEHunter Sheets", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowSheetColors.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Show Skeleton Sheets", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowSheetCorners.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Show Sheet Corners", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowAllPaths.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Show All Loops", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Euclidean to PDB Distance Ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Cost Function:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonAbsoluteDifference.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonNormalizedDifference.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Normalized", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonQuadraticError.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Quadratic", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Loops", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Loop Importance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Euclidean Loop Penalty:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Helices", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Helix Importance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Missing Helix Penalty, Fixed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Missing Helix Penalty, Scaled:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Start or End Missing Helix Penalty:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Sheets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Sheet Importance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Missing Sheet Penalty, Fixed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Missing Sheet Penalty, Scaled:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxIncludeSheets.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Include Sheets", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGraphSettings), QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Border Margin Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setStatusTip(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setWhatsThis(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Max Euclidean Loop Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Helices", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMissingHelices.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Number of Missing Helices:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Sheets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setToolTip(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setStatusTip(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setWhatsThis(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Maximum Sheet Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Sheet Self-Loop Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRebuildGraph.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Rebuild Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Sheet Merging Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setToolTip(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setStatusTip(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setWhatsThis(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "The maximum euclidean distance between possibly connected helices even if they are not connected in the skeleton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Minimum Sheet Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxIncludeStrands.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Include Strands", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMissingSheets.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Number of Missing Sheets:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvancedSettings), QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Advanced Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCorrespondences.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Correspondence:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCorrespondenceList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Predicted SSE", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCorrespondenceList.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Observed SSE", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCorrespondenceList.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Constrained", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonExportToRosetta.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Export Correspondences to Rosetta", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonReset.setText(QtGui.QApplication.translate("DialogSSEHelixCorrespondenceFinder", "Reset", None, QtGui.QApplication.UnicodeUTF8))

