# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_atom_visualization.ui'
#
# Created: Thu Jul 29 17:52:44 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogAtomVisualization(object):
    def setupUi(self, DialogAtomVisualization):
        DialogAtomVisualization.setObjectName("DialogAtomVisualization")
        DialogAtomVisualization.resize(277, 479)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogAtomVisualization.sizePolicy().hasHeightForWidth())
        DialogAtomVisualization.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(DialogAtomVisualization)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(DialogAtomVisualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxDisplayStyle = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxDisplayStyle.sizePolicy().hasHeightForWidth())
        self.groupBoxDisplayStyle.setSizePolicy(sizePolicy)
        self.groupBoxDisplayStyle.setObjectName("groupBoxDisplayStyle")
        self.gridlayout = QtGui.QGridLayout(self.groupBoxDisplayStyle)
        self.gridlayout.setObjectName("gridlayout")
        self.radioButtonBackbone = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonBackbone.setChecked(True)
        self.radioButtonBackbone.setObjectName("radioButtonBackbone")
        self.gridlayout.addWidget(self.radioButtonBackbone, 0, 0, 1, 1)
        self.radioButtonRibbon = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonRibbon.setObjectName("radioButtonRibbon")
        self.gridlayout.addWidget(self.radioButtonRibbon, 0, 1, 1, 1)
        self.radioButtonSideChain = QtGui.QRadioButton(self.groupBoxDisplayStyle)
        self.radioButtonSideChain.setChecked(False)
        self.radioButtonSideChain.setObjectName("radioButtonSideChain")
        self.gridlayout.addWidget(self.radioButtonSideChain, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxDisplayStyle)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBoxBoundingBox = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBoundingBox.sizePolicy().hasHeightForWidth())
        self.checkBoxBoundingBox.setSizePolicy(sizePolicy)
        self.checkBoxBoundingBox.setChecked(True)
        self.checkBoxBoundingBox.setObjectName("checkBoxBoundingBox")
        self.gridLayout_2.addWidget(self.checkBoxBoundingBox, 0, 0, 1, 1)
        self.pushButtonBoundingBoxColor = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBoundingBoxColor.sizePolicy().hasHeightForWidth())
        self.pushButtonBoundingBoxColor.setSizePolicy(sizePolicy)
        self.pushButtonBoundingBoxColor.setObjectName("pushButtonBoundingBoxColor")
        self.gridLayout_2.addWidget(self.pushButtonBoundingBoxColor, 0, 1, 1, 1)
        self.labelColor1 = QtGui.QLabel(self.tab)
        self.labelColor1.setObjectName("labelColor1")
        self.gridLayout_2.addWidget(self.labelColor1, 1, 0, 1, 1)
        self.pushButtonColor1 = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColor1.sizePolicy().hasHeightForWidth())
        self.pushButtonColor1.setSizePolicy(sizePolicy)
        self.pushButtonColor1.setObjectName("pushButtonColor1")
        self.gridLayout_2.addWidget(self.pushButtonColor1, 1, 1, 1, 1)
        self.labelColor2 = QtGui.QLabel(self.tab)
        self.labelColor2.setObjectName("labelColor2")
        self.gridLayout_2.addWidget(self.labelColor2, 2, 0, 1, 1)
        self.pushButtonColor2 = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColor2.sizePolicy().hasHeightForWidth())
        self.pushButtonColor2.setSizePolicy(sizePolicy)
        self.pushButtonColor2.setObjectName("pushButtonColor2")
        self.gridLayout_2.addWidget(self.pushButtonColor2, 2, 1, 1, 1)
        self.labelColor3 = QtGui.QLabel(self.tab)
        self.labelColor3.setObjectName("labelColor3")
        self.gridLayout_2.addWidget(self.labelColor3, 3, 0, 1, 1)
        self.pushButtonColor3 = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColor3.sizePolicy().hasHeightForWidth())
        self.pushButtonColor3.setSizePolicy(sizePolicy)
        self.pushButtonColor3.setObjectName("pushButtonColor3")
        self.gridLayout_2.addWidget(self.pushButtonColor3, 3, 1, 1, 1)
        self.labelColor4 = QtGui.QLabel(self.tab)
        self.labelColor4.setObjectName("labelColor4")
        self.gridLayout_2.addWidget(self.labelColor4, 4, 0, 1, 1)
        self.pushButtonColor4 = ColoredPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColor4.sizePolicy().hasHeightForWidth())
        self.pushButtonColor4.setSizePolicy(sizePolicy)
        self.pushButtonColor4.setObjectName("pushButtonColor4")
        self.gridLayout_2.addWidget(self.pushButtonColor4, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.labelSmoothness = QtGui.QLabel(self.tab)
        self.labelSmoothness.setObjectName("labelSmoothness")
        self.verticalLayout.addWidget(self.labelSmoothness)
        self.hSliderSmoothness = QtGui.QSlider(self.tab)
        self.hSliderSmoothness.setMinimum(2)
        self.hSliderSmoothness.setMaximum(20)
        self.hSliderSmoothness.setProperty("value", QtCore.QVariant(10))
        self.hSliderSmoothness.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderSmoothness.setTickPosition(QtGui.QSlider.TicksBelow)
        self.hSliderSmoothness.setTickInterval(5)
        self.hSliderSmoothness.setObjectName("hSliderSmoothness")
        self.verticalLayout.addWidget(self.hSliderSmoothness)
        self.labelRoundedness = QtGui.QLabel(self.tab)
        self.labelRoundedness.setObjectName("labelRoundedness")
        self.verticalLayout.addWidget(self.labelRoundedness)
        self.hSliderRoundedness = QtGui.QSlider(self.tab)
        self.hSliderRoundedness.setMinimum(3)
        self.hSliderRoundedness.setMaximum(20)
        self.hSliderRoundedness.setProperty("value", QtCore.QVariant(10))
        self.hSliderRoundedness.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderRoundedness.setTickPosition(QtGui.QSlider.TicksBelow)
        self.hSliderRoundedness.setTickInterval(3)
        self.hSliderRoundedness.setObjectName("hSliderRoundedness")
        self.verticalLayout.addWidget(self.hSliderRoundedness)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.rslider = QtGui.QSlider(self.tab)
        self.rslider.setMaximum(100)
        self.rslider.setPageStep(10)
        self.rslider.setProperty("value", QtCore.QVariant(50))
        self.rslider.setOrientation(QtCore.Qt.Horizontal)
        self.rslider.setObjectName("rslider")
        self.verticalLayout.addWidget(self.rslider)
        self.gslider = QtGui.QSlider(self.tab)
        self.gslider.setMaximum(100)
        self.gslider.setProperty("value", QtCore.QVariant(50))
        self.gslider.setOrientation(QtCore.Qt.Horizontal)
        self.gslider.setObjectName("gslider")
        self.verticalLayout.addWidget(self.gslider)
        self.bslider = QtGui.QSlider(self.tab)
        self.bslider.setMaximum(100)
        self.bslider.setProperty("value", QtCore.QVariant(50))
        self.bslider.setOrientation(QtCore.Qt.Horizontal)
        self.bslider.setObjectName("bslider")
        self.verticalLayout.addWidget(self.bslider)
        self.aslider = QtGui.QSlider(self.tab)
        self.aslider.setMaximum(100)
        self.aslider.setProperty("value", QtCore.QVariant(50))
        self.aslider.setSliderPosition(50)
        self.aslider.setOrientation(QtCore.Qt.Horizontal)
        self.aslider.setObjectName("aslider")
        self.verticalLayout.addWidget(self.aslider)
        self.groupBoxShow = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxShow.sizePolicy().hasHeightForWidth())
        self.groupBoxShow.setSizePolicy(sizePolicy)
        self.groupBoxShow.setObjectName("groupBoxShow")
        self.gridLayout = QtGui.QGridLayout(self.groupBoxShow)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxShowAtoms = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowAtoms.setChecked(True)
        self.checkBoxShowAtoms.setObjectName("checkBoxShowAtoms")
        self.gridLayout.addWidget(self.checkBoxShowAtoms, 0, 0, 1, 1)
        self.checkBoxShowBonds = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowBonds.setChecked(True)
        self.checkBoxShowBonds.setObjectName("checkBoxShowBonds")
        self.gridLayout.addWidget(self.checkBoxShowBonds, 0, 1, 1, 1)
        self.checkBoxShowHelices = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowHelices.setChecked(True)
        self.checkBoxShowHelices.setObjectName("checkBoxShowHelices")
        self.gridLayout.addWidget(self.checkBoxShowHelices, 1, 0, 1, 1)
        self.checkBoxShowStrands = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowStrands.setChecked(True)
        self.checkBoxShowStrands.setObjectName("checkBoxShowStrands")
        self.gridLayout.addWidget(self.checkBoxShowStrands, 1, 1, 1, 1)
        self.checkBoxShowLoops = QtGui.QCheckBox(self.groupBoxShow)
        self.checkBoxShowLoops.setChecked(True)
        self.checkBoxShowLoops.setObjectName("checkBoxShowLoops")
        self.gridLayout.addWidget(self.checkBoxShowLoops, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxShow)
        spacerItem = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridlayout1 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout1.setObjectName("gridlayout1")
        self.GroupBoxLocation_2 = QtGui.QGroupBox(self.tab_2)
        self.GroupBoxLocation_2.setObjectName("GroupBoxLocation_2")
        self.gridlayout2 = QtGui.QGridLayout(self.GroupBoxLocation_2)
        self.gridlayout2.setMargin(6)
        self.gridlayout2.setSpacing(0)
        self.gridlayout2.setObjectName("gridlayout2")
        self.labelSizeX = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeX.sizePolicy().hasHeightForWidth())
        self.labelSizeX.setSizePolicy(sizePolicy)
        self.labelSizeX.setObjectName("labelSizeX")
        self.gridlayout2.addWidget(self.labelSizeX, 0, 0, 1, 1)
        self.doubleSpinBoxSizeX = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeX.setDecimals(8)
        self.doubleSpinBoxSizeX.setMaximum(1e+014)
        self.doubleSpinBoxSizeX.setProperty("value", QtCore.QVariant(1.0))
        self.doubleSpinBoxSizeX.setObjectName("doubleSpinBoxSizeX")
        self.gridlayout2.addWidget(self.doubleSpinBoxSizeX, 0, 1, 1, 1)
        self.labelSizeY = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeY.sizePolicy().hasHeightForWidth())
        self.labelSizeY.setSizePolicy(sizePolicy)
        self.labelSizeY.setObjectName("labelSizeY")
        self.gridlayout2.addWidget(self.labelSizeY, 1, 0, 1, 1)
        self.doubleSpinBoxSizeY = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeY.setDecimals(8)
        self.doubleSpinBoxSizeY.setMaximum(1e+014)
        self.doubleSpinBoxSizeY.setProperty("value", QtCore.QVariant(1.0))
        self.doubleSpinBoxSizeY.setObjectName("doubleSpinBoxSizeY")
        self.gridlayout2.addWidget(self.doubleSpinBoxSizeY, 1, 1, 1, 1)
        self.labelSizeZ = QtGui.QLabel(self.GroupBoxLocation_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSizeZ.sizePolicy().hasHeightForWidth())
        self.labelSizeZ.setSizePolicy(sizePolicy)
        self.labelSizeZ.setObjectName("labelSizeZ")
        self.gridlayout2.addWidget(self.labelSizeZ, 2, 0, 1, 1)
        self.doubleSpinBoxSizeZ = QtGui.QDoubleSpinBox(self.GroupBoxLocation_2)
        self.doubleSpinBoxSizeZ.setDecimals(8)
        self.doubleSpinBoxSizeZ.setMaximum(1e+014)
        self.doubleSpinBoxSizeZ.setProperty("value", QtCore.QVariant(1.0))
        self.doubleSpinBoxSizeZ.setObjectName("doubleSpinBoxSizeZ")
        self.gridlayout2.addWidget(self.doubleSpinBoxSizeZ, 2, 1, 1, 1)
        self.gridlayout1.addWidget(self.GroupBoxLocation_2, 0, 0, 1, 1)
        self.GroupBoxLocation = QtGui.QGroupBox(self.tab_2)
        self.GroupBoxLocation.setObjectName("GroupBoxLocation")
        self.gridlayout3 = QtGui.QGridLayout(self.GroupBoxLocation)
        self.gridlayout3.setMargin(6)
        self.gridlayout3.setSpacing(0)
        self.gridlayout3.setObjectName("gridlayout3")
        self.labelLocationX = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationX.sizePolicy().hasHeightForWidth())
        self.labelLocationX.setSizePolicy(sizePolicy)
        self.labelLocationX.setObjectName("labelLocationX")
        self.gridlayout3.addWidget(self.labelLocationX, 0, 0, 1, 1)
        self.doubleSpinBoxLocationX = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationX.setDecimals(8)
        self.doubleSpinBoxLocationX.setMinimum(-1e+014)
        self.doubleSpinBoxLocationX.setMaximum(1e+014)
        self.doubleSpinBoxLocationX.setProperty("value", QtCore.QVariant(0.0))
        self.doubleSpinBoxLocationX.setObjectName("doubleSpinBoxLocationX")
        self.gridlayout3.addWidget(self.doubleSpinBoxLocationX, 0, 1, 1, 1)
        self.labelLocationY = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationY.sizePolicy().hasHeightForWidth())
        self.labelLocationY.setSizePolicy(sizePolicy)
        self.labelLocationY.setObjectName("labelLocationY")
        self.gridlayout3.addWidget(self.labelLocationY, 1, 0, 1, 1)
        self.doubleSpinBoxLocationY = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationY.setDecimals(8)
        self.doubleSpinBoxLocationY.setMinimum(-1e+014)
        self.doubleSpinBoxLocationY.setMaximum(1e+014)
        self.doubleSpinBoxLocationY.setObjectName("doubleSpinBoxLocationY")
        self.gridlayout3.addWidget(self.doubleSpinBoxLocationY, 1, 1, 1, 1)
        self.labelLocationZ = QtGui.QLabel(self.GroupBoxLocation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocationZ.sizePolicy().hasHeightForWidth())
        self.labelLocationZ.setSizePolicy(sizePolicy)
        self.labelLocationZ.setObjectName("labelLocationZ")
        self.gridlayout3.addWidget(self.labelLocationZ, 2, 0, 1, 1)
        self.doubleSpinBoxLocationZ = QtGui.QDoubleSpinBox(self.GroupBoxLocation)
        self.doubleSpinBoxLocationZ.setDecimals(8)
        self.doubleSpinBoxLocationZ.setMinimum(-1e+014)
        self.doubleSpinBoxLocationZ.setMaximum(1e+014)
        self.doubleSpinBoxLocationZ.setObjectName("doubleSpinBoxLocationZ")
        self.gridlayout3.addWidget(self.doubleSpinBoxLocationZ, 2, 1, 1, 1)
        self.gridlayout1.addWidget(self.GroupBoxLocation, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridlayout4 = QtGui.QGridLayout(self.tab_3)
        self.gridlayout4.setObjectName("gridlayout4")
        self.label_2 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridlayout4.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelModelName = QtGui.QLabel(self.tab_3)
        self.labelModelName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelModelName.setWordWrap(True)
        self.labelModelName.setObjectName("labelModelName")
        self.gridlayout4.addWidget(self.labelModelName, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridlayout4.addWidget(self.label, 1, 0, 1, 1)
        self.labelModelSize = QtGui.QLabel(self.tab_3)
        self.labelModelSize.setObjectName("labelModelSize")
        self.gridlayout4.addWidget(self.labelModelSize, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem1, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridlayout5 = QtGui.QGridLayout()
        self.gridlayout5.setObjectName("gridlayout5")
        self.pushButtonCenter = QtGui.QPushButton(DialogAtomVisualization)
        self.pushButtonCenter.setObjectName("pushButtonCenter")
        self.gridlayout5.addWidget(self.pushButtonCenter, 0, 0, 1, 1)
        self.pushButtonClose = QtGui.QPushButton(DialogAtomVisualization)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridlayout5.addWidget(self.pushButtonClose, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridlayout5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        self.retranslateUi(DialogAtomVisualization)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogAtomVisualization)
        DialogAtomVisualization.setTabOrder(self.tabWidget, self.radioButtonBackbone)
        DialogAtomVisualization.setTabOrder(self.radioButtonBackbone, self.radioButtonRibbon)
        DialogAtomVisualization.setTabOrder(self.radioButtonRibbon, self.radioButtonSideChain)
        DialogAtomVisualization.setTabOrder(self.radioButtonSideChain, self.checkBoxBoundingBox)
        DialogAtomVisualization.setTabOrder(self.checkBoxBoundingBox, self.pushButtonBoundingBoxColor)
        DialogAtomVisualization.setTabOrder(self.pushButtonBoundingBoxColor, self.pushButtonColor1)
        DialogAtomVisualization.setTabOrder(self.pushButtonColor1, self.pushButtonColor2)
        DialogAtomVisualization.setTabOrder(self.pushButtonColor2, self.pushButtonColor3)
        DialogAtomVisualization.setTabOrder(self.pushButtonColor3, self.pushButtonColor4)
        DialogAtomVisualization.setTabOrder(self.pushButtonColor4, self.checkBoxShowAtoms)
        DialogAtomVisualization.setTabOrder(self.checkBoxShowAtoms, self.checkBoxShowBonds)
        DialogAtomVisualization.setTabOrder(self.checkBoxShowBonds, self.checkBoxShowHelices)
        DialogAtomVisualization.setTabOrder(self.checkBoxShowHelices, self.checkBoxShowStrands)
        DialogAtomVisualization.setTabOrder(self.checkBoxShowStrands, self.checkBoxShowLoops)
        DialogAtomVisualization.setTabOrder(self.checkBoxShowLoops, self.pushButtonCenter)
        DialogAtomVisualization.setTabOrder(self.pushButtonCenter, self.pushButtonClose)
        DialogAtomVisualization.setTabOrder(self.pushButtonClose, self.doubleSpinBoxSizeX)
        DialogAtomVisualization.setTabOrder(self.doubleSpinBoxSizeX, self.doubleSpinBoxSizeY)
        DialogAtomVisualization.setTabOrder(self.doubleSpinBoxSizeY, self.doubleSpinBoxSizeZ)
        DialogAtomVisualization.setTabOrder(self.doubleSpinBoxSizeZ, self.doubleSpinBoxLocationX)
        DialogAtomVisualization.setTabOrder(self.doubleSpinBoxLocationX, self.doubleSpinBoxLocationY)
        DialogAtomVisualization.setTabOrder(self.doubleSpinBoxLocationY, self.doubleSpinBoxLocationZ)

    def retranslateUi(self, DialogAtomVisualization):
        DialogAtomVisualization.setWindowTitle(QtGui.QApplication.translate("DialogAtomVisualization", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDisplayStyle.setTitle(QtGui.QApplication.translate("DialogAtomVisualization", "Display Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonBackbone.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Backbone", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRibbon.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Ribbon", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSideChain.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Side Chains", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxBoundingBox.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Show outline box colored:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelColor1.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Color 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelColor2.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Color 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelColor3.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Color 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelColor4.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Color 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSmoothness.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Smoothness", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRoundedness.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Roundedness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogAtomVisualization", "r, g, b, a", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxShow.setTitle(QtGui.QApplication.translate("DialogAtomVisualization", "Show:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowAtoms.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Atoms", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowBonds.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Bonds", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowHelices.setText(QtGui.QApplication.translate("DialogAtomVisualization", "α-helices", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowStrands.setText(QtGui.QApplication.translate("DialogAtomVisualization", "β-strands", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowLoops.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Loops", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogAtomVisualization", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.GroupBoxLocation_2.setTitle(QtGui.QApplication.translate("DialogAtomVisualization", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeX.setText(QtGui.QApplication.translate("DialogAtomVisualization", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeY.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeZ.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.GroupBoxLocation.setTitle(QtGui.QApplication.translate("DialogAtomVisualization", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLocationX.setText(QtGui.QApplication.translate("DialogAtomVisualization", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLocationY.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLocationZ.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogAtomVisualization", "Positioning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogAtomVisualization", "File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelModelName.setText(QtGui.QApplication.translate("DialogAtomVisualization", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Model Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelModelSize.setText(QtGui.QApplication.translate("DialogAtomVisualization", "{X, Y, Z}", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("DialogAtomVisualization", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCenter.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClose.setText(QtGui.QApplication.translate("DialogAtomVisualization", "Unload Model", None, QtGui.QApplication.UnicodeUTF8))

from colored_push_button import ColoredPushButton
