# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ross/Desktop/GorgonEmails/somecodetoplaywith/threeResidues.ui'
#
# Created: Wed Oct  1 16:29:19 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_threeResidues(object):
    def setupUi(self, threeResidues):
        threeResidues.setObjectName("threeResidues")
        threeResidues.resize(595,298)
        self.layoutWidget = QtGui.QWidget(threeResidues)
        self.layoutWidget.setGeometry(QtCore.QRect(13,11,551,251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.undoButton = QtGui.QToolButton(self.layoutWidget)
        self.undoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_2.addWidget(self.undoButton)
        self.redoButton = QtGui.QToolButton(self.layoutWidget)
        self.redoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.redoButton.setObjectName("redoButton")
        self.horizontalLayout_2.addWidget(self.redoButton)
        spacerItem = QtGui.QSpacerItem(38,51,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.mockSidechainsCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.mockSidechainsCheckBox.setObjectName("mockSidechainsCheckBox")
        self.verticalLayout_4.addWidget(self.mockSidechainsCheckBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CAdoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CAdoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.CAdoubleSpinBox.setSizePolicy(sizePolicy)
        self.CAdoubleSpinBox.setMinimumSize(QtCore.QSize(50,0))
        self.CAdoubleSpinBox.setMaximumSize(QtCore.QSize(50,16777215))
        self.CAdoubleSpinBox.setDecimals(1)
        self.CAdoubleSpinBox.setSingleStep(0.1)
        self.CAdoubleSpinBox.setProperty("value",QtCore.QVariant(3.8))
        self.CAdoubleSpinBox.setObjectName("CAdoubleSpinBox")
        self.horizontalLayout_3.addWidget(self.CAdoubleSpinBox)
        self.CAlabel = QtGui.QLabel(self.layoutWidget)
        self.CAlabel.setObjectName("CAlabel")
        self.horizontalLayout_3.addWidget(self.CAlabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtGui.QSpacerItem(38,51,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.acceptButton = QtGui.QPushButton(self.layoutWidget)
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_5.addWidget(self.acceptButton)
        spacerItem2 = QtGui.QSpacerItem(38,51,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.helixTab = QtGui.QWidget()
        self.helixTab.setGeometry(QtCore.QRect(0,0,200,219))
        self.helixTab.setObjectName("helixTab")
        self.tabWidget.addTab(self.helixTab,"")
        self.atomicTab = QtGui.QWidget()
        self.atomicTab.setGeometry(QtCore.QRect(0,0,200,219))
        self.atomicTab.setObjectName("atomicTab")
        self.layoutWidget_3 = QtGui.QWidget(self.atomicTab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10,0,177,216))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setContentsMargins(-1,-1,0,0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.possibilityNumSpinBox = QtGui.QSpinBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.possibilityNumSpinBox.sizePolicy().hasHeightForWidth())
        self.possibilityNumSpinBox.setSizePolicy(sizePolicy)
        self.possibilityNumSpinBox.setMinimumSize(QtCore.QSize(50,0))
        self.possibilityNumSpinBox.setMaximumSize(QtCore.QSize(50,16777215))
        self.possibilityNumSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.possibilityNumSpinBox.setProperty("value",QtCore.QVariant(1))
        self.possibilityNumSpinBox.setObjectName("possibilityNumSpinBox")
        self.horizontalLayout_8.addWidget(self.possibilityNumSpinBox)
        self.numPossibilitiesLabel = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numPossibilitiesLabel.sizePolicy().hasHeightForWidth())
        self.numPossibilitiesLabel.setSizePolicy(sizePolicy)
        self.numPossibilitiesLabel.setObjectName("numPossibilitiesLabel")
        self.horizontalLayout_8.addWidget(self.numPossibilitiesLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevRes = QtGui.QVBoxLayout()
        self.prevRes.setObjectName("prevRes")
        self.prevNum = QtGui.QLabel(self.layoutWidget_3)
        self.prevNum.setAlignment(QtCore.Qt.AlignCenter)
        self.prevNum.setObjectName("prevNum")
        self.prevRes.addWidget(self.prevNum)
        self.prevName = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(41)
        self.prevName.setFont(font)
        self.prevName.setAlignment(QtCore.Qt.AlignCenter)
        self.prevName.setObjectName("prevName")
        self.prevRes.addWidget(self.prevName)
        self.horizontalLayout.addLayout(self.prevRes)
        self.currentRes = QtGui.QVBoxLayout()
        self.currentRes.setObjectName("currentRes")
        self.curNum = QtGui.QLabel(self.layoutWidget_3)
        self.curNum.setAlignment(QtCore.Qt.AlignCenter)
        self.curNum.setObjectName("curNum")
        self.currentRes.addWidget(self.curNum)
        self.curName = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(41)
        self.curName.setFont(font)
        self.curName.setAlignment(QtCore.Qt.AlignCenter)
        self.curName.setObjectName("curName")
        self.currentRes.addWidget(self.curName)
        self.horizontalLayout.addLayout(self.currentRes)
        self.nextRes = QtGui.QVBoxLayout()
        self.nextRes.setObjectName("nextRes")
        self.nextNum = QtGui.QLabel(self.layoutWidget_3)
        self.nextNum.setAlignment(QtCore.Qt.AlignCenter)
        self.nextNum.setObjectName("nextNum")
        self.nextRes.addWidget(self.nextNum)
        self.nextName = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(41)
        self.nextName.setFont(font)
        self.nextName.setAlignment(QtCore.Qt.AlignCenter)
        self.nextName.setObjectName("nextName")
        self.nextRes.addWidget(self.nextName)
        self.horizontalLayout.addLayout(self.nextRes)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back1resButton = QtGui.QPushButton(self.layoutWidget_3)
        self.back1resButton.setObjectName("back1resButton")
        self.horizontalLayout_7.addWidget(self.back1resButton)
        self.forward1resButton = QtGui.QPushButton(self.layoutWidget_3)
        self.forward1resButton.setObjectName("forward1resButton")
        self.horizontalLayout_7.addWidget(self.forward1resButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.atomicTab,"")
        self.loopTab = QtGui.QWidget()
        self.loopTab.setGeometry(QtCore.QRect(0,0,200,219))
        self.loopTab.setObjectName("loopTab")
        self.tabWidget.addTab(self.loopTab,"")
        self.horizontalLayout_6.addWidget(self.tabWidget)

        self.retranslateUi(threeResidues)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(threeResidues)

    def retranslateUi(self, threeResidues):
        threeResidues.setWindowTitle(QtGui.QApplication.translate("threeResidues", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setText(QtGui.QApplication.translate("threeResidues", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setText(QtGui.QApplication.translate("threeResidues", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.mockSidechainsCheckBox.setText(QtGui.QApplication.translate("threeResidues", "Mock Sidechains", None, QtGui.QApplication.UnicodeUTF8))
        self.CAlabel.setText(QtGui.QApplication.translate("threeResidues", "C-Alpha Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptButton.setText(QtGui.QApplication.translate("threeResidues", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helixTab), QtGui.QApplication.translate("threeResidues", "Helix Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.numPossibilitiesLabel.setText(QtGui.QApplication.translate("threeResidues", "/ 3", None, QtGui.QApplication.UnicodeUTF8))
        self.prevNum.setText(QtGui.QApplication.translate("threeResidues", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#666666;\">167</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.prevName.setText(QtGui.QApplication.translate("threeResidues", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:41pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#666666;\">A</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.curNum.setText(QtGui.QApplication.translate("threeResidues", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffff00;\">168</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.curName.setText(QtGui.QApplication.translate("threeResidues", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:41pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffff00;\">Q</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.nextNum.setText(QtGui.QApplication.translate("threeResidues", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#008000;\">169</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.nextName.setText(QtGui.QApplication.translate("threeResidues", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:41pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#008000;\">F</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.back1resButton.setText(QtGui.QApplication.translate("threeResidues", "<-", None, QtGui.QApplication.UnicodeUTF8))
        self.forward1resButton.setText(QtGui.QApplication.translate("threeResidues", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.atomicTab), QtGui.QApplication.translate("threeResidues", "Atomic Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loopTab), QtGui.QApplication.translate("threeResidues", "Loop Editor", None, QtGui.QApplication.UnicodeUTF8))

