# qmake project generated by QMsDev
#
# General settings

TEMPLATE = app
CONFIG  += qt warn_off x11 opengl link_prl
TARGET  += MRCRawIVConverter

unix:LIBS += ByteOrder/libByteOrder.a
unix:LIBS += VolumeFileTypes/libVolumeFileTypes.a

unix:LIBS += /usr/lib/libCgGL.so
unix:LIBS += /usr/lib/libpthread.so
unix:LIBS += -lqassistantclient

# Input

INCLUDEPATH += ./VolumeFileTypes
INCLUDEPATH += ./ByteOrder

SOURCES =  \
		main.cpp \
		SimpleVolumeData.cpp 

HEADERS =  \
		SimpleVolumeData.h 

